/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AuthChangePasswordCreate200,
  AuthLoginCreate200,
  AuthLogoutCreate200,
  AuthMePartialUpdate200,
  AuthMeRetrieve200,
  AuthRefreshCreate200,
  ChangePasswordRequest,
  CustomTokenObtainPairRequest,
  LogoutRequestRequest,
  PatchedUpdateProfileRequest,
  RefreshRequestRequest,
} from "../../model";
import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const authChangePasswordCreate = (
  changePasswordRequest: ChangePasswordRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuthChangePasswordCreate200>(
    {
      url: `/api/v1/auth/change-password/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: changePasswordRequest,
    },
    options,
  );
};

export const getAuthChangePasswordCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authChangePasswordCreate>>,
    TError,
    { data: ChangePasswordRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authChangePasswordCreate>>,
  TError,
  { data: ChangePasswordRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authChangePasswordCreate>>,
    { data: ChangePasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authChangePasswordCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthChangePasswordCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authChangePasswordCreate>>
>;
export type AuthChangePasswordCreateMutationBody = ChangePasswordRequest;
export type AuthChangePasswordCreateMutationError = unknown;

export const useAuthChangePasswordCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authChangePasswordCreate>>,
    TError,
    { data: ChangePasswordRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof authChangePasswordCreate>>,
  TError,
  { data: ChangePasswordRequest },
  TContext
> => {
  const mutationOptions = getAuthChangePasswordCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const authLoginCreate = (
  customTokenObtainPairRequest: CustomTokenObtainPairRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuthLoginCreate200>(
    {
      url: `/api/v1/auth/login/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: customTokenObtainPairRequest,
    },
    options,
  );
};

export const getAuthLoginCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLoginCreate>>,
    TError,
    { data: CustomTokenObtainPairRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: CustomTokenObtainPairRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLoginCreate>>,
    { data: CustomTokenObtainPairRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authLoginCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLoginCreate>>
>;
export type AuthLoginCreateMutationBody = CustomTokenObtainPairRequest;
export type AuthLoginCreateMutationError = unknown;

export const useAuthLoginCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLoginCreate>>,
    TError,
    { data: CustomTokenObtainPairRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof authLoginCreate>>,
  TError,
  { data: CustomTokenObtainPairRequest },
  TContext
> => {
  const mutationOptions = getAuthLoginCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authLogoutCreate = (
  logoutRequestRequest: LogoutRequestRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuthLogoutCreate200>(
    {
      url: `/api/v1/auth/logout/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: logoutRequestRequest,
    },
    options,
  );
};

export const getAuthLogoutCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    TError,
    { data: LogoutRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogoutCreate>>,
  TError,
  { data: LogoutRequestRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    { data: LogoutRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authLogoutCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLogoutCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authLogoutCreate>>
>;
export type AuthLogoutCreateMutationBody = LogoutRequestRequest;
export type AuthLogoutCreateMutationError = unknown;

export const useAuthLogoutCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogoutCreate>>,
    TError,
    { data: LogoutRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof authLogoutCreate>>,
  TError,
  { data: LogoutRequestRequest },
  TContext
> => {
  const mutationOptions = getAuthLogoutCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const authMeRetrieve = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthMeRetrieve200>(
    { url: `/api/v1/auth/me/`, method: "GET", signal },
    options,
  );
};

export const getAuthMeRetrieveQueryKey = () => {
  return [`/api/v1/auth/me/`] as const;
};

export const getAuthMeRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthMeRetrieveQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authMeRetrieve>>> = ({
    signal,
  }) => authMeRetrieve(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authMeRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AuthMeRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof authMeRetrieve>>
>;
export type AuthMeRetrieveQueryError = unknown;

export const useAuthMeRetrieve = <
  TData = Awaited<ReturnType<typeof authMeRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authMeRetrieve>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAuthMeRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const authMePartialUpdate = (
  patchedUpdateProfileRequest: PatchedUpdateProfileRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuthMePartialUpdate200>(
    {
      url: `/api/v1/auth/me/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedUpdateProfileRequest,
    },
    options,
  );
};

export const getAuthMePartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authMePartialUpdate>>,
    TError,
    { data: PatchedUpdateProfileRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authMePartialUpdate>>,
  TError,
  { data: PatchedUpdateProfileRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authMePartialUpdate>>,
    { data: PatchedUpdateProfileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authMePartialUpdate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthMePartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authMePartialUpdate>>
>;
export type AuthMePartialUpdateMutationBody = PatchedUpdateProfileRequest;
export type AuthMePartialUpdateMutationError = unknown;

export const useAuthMePartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authMePartialUpdate>>,
    TError,
    { data: PatchedUpdateProfileRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof authMePartialUpdate>>,
  TError,
  { data: PatchedUpdateProfileRequest },
  TContext
> => {
  const mutationOptions = getAuthMePartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authRefreshCreate = (
  refreshRequestRequest: RefreshRequestRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<AuthRefreshCreate200>(
    {
      url: `/api/v1/auth/refresh/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: refreshRequestRequest,
    },
    options,
  );
};

export const getAuthRefreshCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRefreshCreate>>,
    TError,
    { data: RefreshRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRefreshCreate>>,
  TError,
  { data: RefreshRequestRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRefreshCreate>>,
    { data: RefreshRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return authRefreshCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRefreshCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof authRefreshCreate>>
>;
export type AuthRefreshCreateMutationBody = RefreshRequestRequest;
export type AuthRefreshCreateMutationError = unknown;

export const useAuthRefreshCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRefreshCreate>>,
    TError,
    { data: RefreshRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof authRefreshCreate>>,
  TError,
  { data: RefreshRequestRequest },
  TContext
> => {
  const mutationOptions = getAuthRefreshCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
