/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

export const chatCreateBodyMessageMax = 2000;


export const chatCreateBody = zod.object({
  "session_id": zod.string().uuid().nullish(),
  "session_token": zod.string().min(1).nullish(),
  "message": zod.string().min(1).max(chatCreateBodyMessageMax),
  "metadata": zod.any().nullish()
})

export const chatCreateResponseDataMessageMax = 2000;


export const chatCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "session_id": zod.string().uuid().nullish(),
  "session_token": zod.string().nullish(),
  "message": zod.string().max(chatCreateResponseDataMessageMax),
  "metadata": zod.any().nullish()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const chatFeedbackCreateBodyCommentMax = 1000;


export const chatFeedbackCreateBody = zod.object({
  "session_id": zod.string().uuid(),
  "session_token": zod.string().min(1),
  "message_id": zod.number().nullish(),
  "rating": zod.enum(['positive', 'negative']),
  "comment": zod.string().max(chatFeedbackCreateBodyCommentMax).optional()
})

export const chatFeedbackCreateResponseDataCommentMax = 1000;


export const chatFeedbackCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "rating": zod.enum(['positive', 'negative']),
  "comment": zod.string().max(chatFeedbackCreateResponseDataCommentMax).optional()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const chatSessionsCreateBodySourceChannelMax = 50;


export const chatSessionsCreateBody = zod.object({
  "source_channel": zod.string().min(1).max(chatSessionsCreateBodySourceChannelMax).optional()
})

export const chatSessionsCreateResponseDataSourceChannelMax = 50;


export const chatSessionsCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "source_channel": zod.string().max(chatSessionsCreateResponseDataSourceChannelMax).optional()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

