/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  AnalyticEventRequest,
  PatchedAnalyticEventRequest,
  PlatformAnalyticsDashboardExecutiveRetrieve200,
  PlatformAnalyticsEventsCreate201,
  PlatformAnalyticsEventsList200,
  PlatformAnalyticsEventsListParams,
  PlatformAnalyticsEventsPartialUpdate200,
  PlatformAnalyticsEventsRetrieve200,
  PlatformAnalyticsEventsUpdate200,
} from "../../model";
import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Executive Dashboard KPI Aggregations.
Flat structured return using DB-level aggregations.
 */
export const platformAnalyticsDashboardExecutiveRetrieve = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PlatformAnalyticsDashboardExecutiveRetrieve200>(
    {
      url: `/api/v1/platform/analytics/dashboard/executive/`,
      method: "GET",
      signal,
    },
    options,
  );
};

export const getPlatformAnalyticsDashboardExecutiveRetrieveQueryKey = () => {
  return [`/api/v1/platform/analytics/dashboard/executive/`] as const;
};

export const getPlatformAnalyticsDashboardExecutiveRetrieveQueryOptions = <
  TData = Awaited<
    ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPlatformAnalyticsDashboardExecutiveRetrieveQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>>
  > = ({ signal }) =>
    platformAnalyticsDashboardExecutiveRetrieve(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformAnalyticsDashboardExecutiveRetrieveQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>>
  >;
export type PlatformAnalyticsDashboardExecutiveRetrieveQueryError = unknown;

export const usePlatformAnalyticsDashboardExecutiveRetrieve = <
  TData = Awaited<
    ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof platformAnalyticsDashboardExecutiveRetrieve>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getPlatformAnalyticsDashboardExecutiveRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const platformAnalyticsEventsList = (
  params?: PlatformAnalyticsEventsListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PlatformAnalyticsEventsList200>(
    {
      url: `/api/v1/platform/analytics/events/`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getPlatformAnalyticsEventsListQueryKey = (
  params?: PlatformAnalyticsEventsListParams,
) => {
  return [
    `/api/v1/platform/analytics/events/`,
    ...(params ? [params] : []),
  ] as const;
};

export const getPlatformAnalyticsEventsListQueryOptions = <
  TData = Awaited<ReturnType<typeof platformAnalyticsEventsList>>,
  TError = unknown,
>(
  params?: PlatformAnalyticsEventsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof platformAnalyticsEventsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPlatformAnalyticsEventsListQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof platformAnalyticsEventsList>>
  > = ({ signal }) =>
    platformAnalyticsEventsList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformAnalyticsEventsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof platformAnalyticsEventsList>>
>;
export type PlatformAnalyticsEventsListQueryError = unknown;

export const usePlatformAnalyticsEventsList = <
  TData = Awaited<ReturnType<typeof platformAnalyticsEventsList>>,
  TError = unknown,
>(
  params?: PlatformAnalyticsEventsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof platformAnalyticsEventsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getPlatformAnalyticsEventsListQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const platformAnalyticsEventsCreate = (
  analyticEventRequest: AnalyticEventRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PlatformAnalyticsEventsCreate201>(
    {
      url: `/api/v1/platform/analytics/events/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: analyticEventRequest,
    },
    options,
  );
};

export const getPlatformAnalyticsEventsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsCreate>>,
    TError,
    { data: AnalyticEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformAnalyticsEventsCreate>>,
  TError,
  { data: AnalyticEventRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformAnalyticsEventsCreate>>,
    { data: AnalyticEventRequest }
  > = (props) => {
    const { data } = props ?? {};

    return platformAnalyticsEventsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformAnalyticsEventsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformAnalyticsEventsCreate>>
>;
export type PlatformAnalyticsEventsCreateMutationBody = AnalyticEventRequest;
export type PlatformAnalyticsEventsCreateMutationError = unknown;

export const usePlatformAnalyticsEventsCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsCreate>>,
    TError,
    { data: AnalyticEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformAnalyticsEventsCreate>>,
  TError,
  { data: AnalyticEventRequest },
  TContext
> => {
  const mutationOptions =
    getPlatformAnalyticsEventsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const platformAnalyticsEventsRetrieve = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PlatformAnalyticsEventsRetrieve200>(
    { url: `/api/v1/platform/analytics/events/${id}/`, method: "GET", signal },
    options,
  );
};

export const getPlatformAnalyticsEventsRetrieveQueryKey = (id: string) => {
  return [`/api/v1/platform/analytics/events/${id}/`] as const;
};

export const getPlatformAnalyticsEventsRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPlatformAnalyticsEventsRetrieveQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>
  > = ({ signal }) =>
    platformAnalyticsEventsRetrieve(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type PlatformAnalyticsEventsRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>
>;
export type PlatformAnalyticsEventsRetrieveQueryError = unknown;

export const usePlatformAnalyticsEventsRetrieve = <
  TData = Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof platformAnalyticsEventsRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getPlatformAnalyticsEventsRetrieveQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const platformAnalyticsEventsUpdate = (
  id: string,
  analyticEventRequest: AnalyticEventRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PlatformAnalyticsEventsUpdate200>(
    {
      url: `/api/v1/platform/analytics/events/${id}/`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: analyticEventRequest,
    },
    options,
  );
};

export const getPlatformAnalyticsEventsUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsUpdate>>,
    TError,
    { id: string; data: AnalyticEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformAnalyticsEventsUpdate>>,
  TError,
  { id: string; data: AnalyticEventRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformAnalyticsEventsUpdate>>,
    { id: string; data: AnalyticEventRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return platformAnalyticsEventsUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformAnalyticsEventsUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformAnalyticsEventsUpdate>>
>;
export type PlatformAnalyticsEventsUpdateMutationBody = AnalyticEventRequest;
export type PlatformAnalyticsEventsUpdateMutationError = unknown;

export const usePlatformAnalyticsEventsUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsUpdate>>,
    TError,
    { id: string; data: AnalyticEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformAnalyticsEventsUpdate>>,
  TError,
  { id: string; data: AnalyticEventRequest },
  TContext
> => {
  const mutationOptions =
    getPlatformAnalyticsEventsUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const platformAnalyticsEventsPartialUpdate = (
  id: string,
  patchedAnalyticEventRequest: PatchedAnalyticEventRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<PlatformAnalyticsEventsPartialUpdate200>(
    {
      url: `/api/v1/platform/analytics/events/${id}/`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchedAnalyticEventRequest,
    },
    options,
  );
};

export const getPlatformAnalyticsEventsPartialUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsPartialUpdate>>,
    TError,
    { id: string; data: PatchedAnalyticEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformAnalyticsEventsPartialUpdate>>,
  TError,
  { id: string; data: PatchedAnalyticEventRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformAnalyticsEventsPartialUpdate>>,
    { id: string; data: PatchedAnalyticEventRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return platformAnalyticsEventsPartialUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformAnalyticsEventsPartialUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformAnalyticsEventsPartialUpdate>>
>;
export type PlatformAnalyticsEventsPartialUpdateMutationBody =
  PatchedAnalyticEventRequest;
export type PlatformAnalyticsEventsPartialUpdateMutationError = unknown;

export const usePlatformAnalyticsEventsPartialUpdate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsPartialUpdate>>,
    TError,
    { id: string; data: PatchedAnalyticEventRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformAnalyticsEventsPartialUpdate>>,
  TError,
  { id: string; data: PatchedAnalyticEventRequest },
  TContext
> => {
  const mutationOptions =
    getPlatformAnalyticsEventsPartialUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const platformAnalyticsEventsDestroy = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/api/v1/platform/analytics/events/${id}/`, method: "DELETE" },
    options,
  );
};

export const getPlatformAnalyticsEventsDestroyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsDestroy>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof platformAnalyticsEventsDestroy>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof platformAnalyticsEventsDestroy>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return platformAnalyticsEventsDestroy(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PlatformAnalyticsEventsDestroyMutationResult = NonNullable<
  Awaited<ReturnType<typeof platformAnalyticsEventsDestroy>>
>;

export type PlatformAnalyticsEventsDestroyMutationError = unknown;

export const usePlatformAnalyticsEventsDestroy = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof platformAnalyticsEventsDestroy>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof platformAnalyticsEventsDestroy>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions =
    getPlatformAnalyticsEventsDestroyMutationOptions(options);

  return useMutation(mutationOptions);
};
