/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * Returns 200 alive status if the application process is running.
 * @summary Liveness Probe
 */
export const apiHealthLiveRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "status": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

/**
 * Checks Database, Cache, and environment readiness.
 * @summary Readiness Probe
 */
export const apiHealthReadyRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "status": zod.string(),
  "checks": zod.string(),
  "timestamp": zod.string().datetime()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

/**
 * Comprehensive infrastructure telemetry including latency, version, and uptime.
 * @summary System Telemetry & Health
 */
export const apiHealthSystemRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "status": zod.string(),
  "version": zod.string(),
  "git_commit": zod.string(),
  "uptime_seconds": zod.number(),
  "environment": zod.string(),
  "python_version": zod.string(),
  "django_version": zod.string(),
  "telemetry": zod.string(),
  "timestamp": zod.string().datetime()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

