/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * Executive Dashboard KPI Aggregations.
Flat structured return using DB-level aggregations.
 */
export const platformAnalyticsDashboardExecutiveRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.record(zod.string(), zod.any()),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const platformAnalyticsEventsListQueryParams = zod.object({
  "category": zod.enum(['AI', 'Business', 'Consultation', 'Lab', 'Operations', 'Website']).optional(),
  "ordering": zod.string().optional(),
  "page": zod.number().optional(),
  "search": zod.string().optional()
})

export const platformAnalyticsEventsListResponseDataResultsItemSessionCookieIdMax = 255;
export const platformAnalyticsEventsListResponseDataResultsItemEventNameMax = 100;
export const platformAnalyticsEventsListResponseDataResultsItemUrlMax = 200;
export const platformAnalyticsEventsListResponseDataResultsItemRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsListResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "count": zod.number(),
  "next": zod.string().url().nullish(),
  "previous": zod.string().url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.string().uuid(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime(),
  "session_cookie_id": zod.string().max(platformAnalyticsEventsListResponseDataResultsItemSessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']),
  "event_name": zod.string().max(platformAnalyticsEventsListResponseDataResultsItemEventNameMax),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsListResponseDataResultsItemUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsListResponseDataResultsItemRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
}))
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const platformAnalyticsEventsCreateBodySessionCookieIdMax = 255;
export const platformAnalyticsEventsCreateBodyEventNameMax = 100;
export const platformAnalyticsEventsCreateBodyUrlMax = 200;
export const platformAnalyticsEventsCreateBodyRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsCreateBody = zod.object({
  "session_cookie_id": zod.string().max(platformAnalyticsEventsCreateBodySessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']),
  "event_name": zod.string().min(1).max(platformAnalyticsEventsCreateBodyEventNameMax),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsCreateBodyUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsCreateBodyRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
})

export const platformAnalyticsEventsRetrieveParams = zod.object({
  "id": zod.string().uuid()
})

export const platformAnalyticsEventsRetrieveResponseDataSessionCookieIdMax = 255;
export const platformAnalyticsEventsRetrieveResponseDataEventNameMax = 100;
export const platformAnalyticsEventsRetrieveResponseDataUrlMax = 200;
export const platformAnalyticsEventsRetrieveResponseDataRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string().uuid(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime(),
  "session_cookie_id": zod.string().max(platformAnalyticsEventsRetrieveResponseDataSessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']),
  "event_name": zod.string().max(platformAnalyticsEventsRetrieveResponseDataEventNameMax),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsRetrieveResponseDataUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsRetrieveResponseDataRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const platformAnalyticsEventsUpdateParams = zod.object({
  "id": zod.string().uuid()
})

export const platformAnalyticsEventsUpdateBodySessionCookieIdMax = 255;
export const platformAnalyticsEventsUpdateBodyEventNameMax = 100;
export const platformAnalyticsEventsUpdateBodyUrlMax = 200;
export const platformAnalyticsEventsUpdateBodyRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsUpdateBody = zod.object({
  "session_cookie_id": zod.string().max(platformAnalyticsEventsUpdateBodySessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']),
  "event_name": zod.string().min(1).max(platformAnalyticsEventsUpdateBodyEventNameMax),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsUpdateBodyUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsUpdateBodyRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
})

export const platformAnalyticsEventsUpdateResponseDataSessionCookieIdMax = 255;
export const platformAnalyticsEventsUpdateResponseDataEventNameMax = 100;
export const platformAnalyticsEventsUpdateResponseDataUrlMax = 200;
export const platformAnalyticsEventsUpdateResponseDataRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsUpdateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string().uuid(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime(),
  "session_cookie_id": zod.string().max(platformAnalyticsEventsUpdateResponseDataSessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']),
  "event_name": zod.string().max(platformAnalyticsEventsUpdateResponseDataEventNameMax),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsUpdateResponseDataUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsUpdateResponseDataRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const platformAnalyticsEventsPartialUpdateParams = zod.object({
  "id": zod.string().uuid()
})

export const platformAnalyticsEventsPartialUpdateBodySessionCookieIdMax = 255;
export const platformAnalyticsEventsPartialUpdateBodyEventNameMax = 100;
export const platformAnalyticsEventsPartialUpdateBodyUrlMax = 200;
export const platformAnalyticsEventsPartialUpdateBodyRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsPartialUpdateBody = zod.object({
  "session_cookie_id": zod.string().max(platformAnalyticsEventsPartialUpdateBodySessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']).optional(),
  "event_name": zod.string().min(1).max(platformAnalyticsEventsPartialUpdateBodyEventNameMax).optional(),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsPartialUpdateBodyUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsPartialUpdateBodyRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
})

export const platformAnalyticsEventsPartialUpdateResponseDataSessionCookieIdMax = 255;
export const platformAnalyticsEventsPartialUpdateResponseDataEventNameMax = 100;
export const platformAnalyticsEventsPartialUpdateResponseDataUrlMax = 200;
export const platformAnalyticsEventsPartialUpdateResponseDataRevenueAmountRegExp = new RegExp('^-?\\d{0,10}(?:\\.\\d{0,2})?$');


export const platformAnalyticsEventsPartialUpdateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string().uuid(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime(),
  "session_cookie_id": zod.string().max(platformAnalyticsEventsPartialUpdateResponseDataSessionCookieIdMax).nullish(),
  "category": zod.enum(['Website', 'AI', 'Lab', 'Business', 'Consultation', 'Operations']),
  "event_name": zod.string().max(platformAnalyticsEventsPartialUpdateResponseDataEventNameMax),
  "metadata": zod.any().optional(),
  "url": zod.string().url().max(platformAnalyticsEventsPartialUpdateResponseDataUrlMax).nullish(),
  "revenue_amount": zod.string().regex(platformAnalyticsEventsPartialUpdateResponseDataRevenueAmountRegExp).optional(),
  "user": zod.string().uuid().nullish(),
  "intelligence_profile": zod.string().uuid().nullish()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const platformAnalyticsEventsDestroyParams = zod.object({
  "id": zod.string().uuid()
})

