/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  KbEntriesList200,
  KbEntriesListParams,
  KbEntriesRetrieve200,
} from "../../model";
import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary List published knowledge base articles (public)
 */
export const kbEntriesList = (
  params?: KbEntriesListParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<KbEntriesList200>(
    { url: `/api/v1/kb/entries/`, method: "GET", params, signal },
    options,
  );
};

export const getKbEntriesListQueryKey = (params?: KbEntriesListParams) => {
  return [`/api/v1/kb/entries/`, ...(params ? [params] : [])] as const;
};

export const getKbEntriesListQueryOptions = <
  TData = Awaited<ReturnType<typeof kbEntriesList>>,
  TError = unknown,
>(
  params?: KbEntriesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kbEntriesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getKbEntriesListQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof kbEntriesList>>> = ({
    signal,
  }) => kbEntriesList(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof kbEntriesList>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type KbEntriesListQueryResult = NonNullable<
  Awaited<ReturnType<typeof kbEntriesList>>
>;
export type KbEntriesListQueryError = unknown;

/**
 * @summary List published knowledge base articles (public)
 */
export const useKbEntriesList = <
  TData = Awaited<ReturnType<typeof kbEntriesList>>,
  TError = unknown,
>(
  params?: KbEntriesListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kbEntriesList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getKbEntriesListQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Retrieve a published knowledge base article by slug (public)
 */
export const kbEntriesRetrieve = (
  slug: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<KbEntriesRetrieve200>(
    { url: `/api/v1/kb/entries/${slug}/`, method: "GET", signal },
    options,
  );
};

export const getKbEntriesRetrieveQueryKey = (slug: string) => {
  return [`/api/v1/kb/entries/${slug}/`] as const;
};

export const getKbEntriesRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof kbEntriesRetrieve>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof kbEntriesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getKbEntriesRetrieveQueryKey(slug);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof kbEntriesRetrieve>>
  > = ({ signal }) => kbEntriesRetrieve(slug, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!slug,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof kbEntriesRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type KbEntriesRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof kbEntriesRetrieve>>
>;
export type KbEntriesRetrieveQueryError = unknown;

/**
 * @summary Retrieve a published knowledge base article by slug (public)
 */
export const useKbEntriesRetrieve = <
  TData = Awaited<ReturnType<typeof kbEntriesRetrieve>>,
  TError = unknown,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof kbEntriesRetrieve>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getKbEntriesRetrieveQueryOptions(slug, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
