/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `public` - Public
 * `private` - Private
 * `tenant_restricted` - Tenant Restricted
 */
export type AccessLevelEnum =
  (typeof AccessLevelEnum)[keyof typeof AccessLevelEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccessLevelEnum = {
  public: "public",
  private: "private",
  tenant_restricted: "tenant_restricted",
} as const;
