/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `lead_created` - Lead Created
 * `lead_qualified` - Lead Qualified
 * `email_sent` - Email Sent
 * `status_changed` - Status Changed
 * `followup_created` - Follow-up Created
 * `followup_completed` - Follow-up Completed
 * `note_added` - Note Added
 * `assignment` - Assignment
 */
export type ActivityTypeEnum =
  (typeof ActivityTypeEnum)[keyof typeof ActivityTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityTypeEnum = {
  lead_created: "lead_created",
  lead_qualified: "lead_qualified",
  email_sent: "email_sent",
  status_changed: "status_changed",
  followup_created: "followup_created",
  followup_completed: "followup_completed",
  note_added: "note_added",
  assignment: "assignment",
} as const;
