/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KnowledgeEntryVersionDetail } from "./knowledgeEntryVersionDetail";
import type { AdminKnowledgeVersionsRetrieve200Meta } from "./adminKnowledgeVersionsRetrieve200Meta";

export type AdminKnowledgeVersionsRetrieve200 = {
  data: KnowledgeEntryVersionDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKnowledgeVersionsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
