/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { UserDetail } from "./userDetail";
import type { AdminUsersMeRetrieve200Meta } from "./adminUsersMeRetrieve200Meta";

export type AdminUsersMeRetrieve200 = {
  data: UserDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminUsersMeRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
