/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Payment } from "./payment";
import type { AdminBusinessPaymentsUpdate200Meta } from "./adminBusinessPaymentsUpdate200Meta";

export type AdminBusinessPaymentsUpdate200 = {
  data: Payment;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessPaymentsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
