/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationReport } from "./consultationReport";
import type { AdminEngagementReportsCreate201Meta } from "./adminEngagementReportsCreate201Meta";

export type AdminEngagementReportsCreate201 = {
  data: ConsultationReport;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementReportsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
