/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAssetsReportsListAccessLevel } from "./adminAssetsReportsListAccessLevel";
import type { AdminAssetsReportsListAssetType } from "./adminAssetsReportsListAssetType";

export type AdminAssetsReportsListParams = {
  /**
   * * `public` - Public
   * `private` - Private
   * `tenant_restricted` - Tenant Restricted
   */
  access_level?: AdminAssetsReportsListAccessLevel;
  /**
   * * `image` - Image
   * `video` - Video
   * `pdf_report` - PDF Report
   * `invoice` - Invoice
   * `contract` - Contract
   * `other` - Other
   */
  asset_type?: AdminAssetsReportsListAssetType;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * A search term.
   */
  search?: string;
  storage_provider?: string;
};
