/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessageTypeEnum } from "./messageTypeEnum";
import type { RoleEnum } from "./roleEnum";

export interface AdminMessage {
  content: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  context_size?: number | null;
  readonly created_at: string;
  /** @nullable */
  deleted_at?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  error_code?: string | null;
  /** @nullable */
  error_detail?: string | null;
  readonly id: number;
  is_deleted?: boolean;
  knowledge_retrieved?: string;
  message_type?: MessageTypeEnum;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  processing_time_ms?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  prompt_size?: number | null;
  response_metadata?: string;
  role: RoleEnum;
  scope_guard_refusal?: boolean;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  sequence_number: number | null;
  session: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  token_count_input?: number | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  token_count_output?: number | null;
}
