/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { UserIds } from "./userIds";
import type { AdminRolesRemoveUsersCreate200Meta } from "./adminRolesRemoveUsersCreate200Meta";

export type AdminRolesRemoveUsersCreate200 = {
  data: UserIds;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminRolesRemoveUsersCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
