/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedContactList } from "./paginatedContactList";
import type { AdminBusinessContactsList200Meta } from "./adminBusinessContactsList200Meta";

export type AdminBusinessContactsList200 = {
  data: PaginatedContactList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessContactsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
