/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Consultation } from "./consultation";
import type { AdminBusinessConsultationsPartialUpdate200Meta } from "./adminBusinessConsultationsPartialUpdate200Meta";

export type AdminBusinessConsultationsPartialUpdate200 = {
  data: Consultation;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessConsultationsPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
