/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TeamMember } from "./teamMember";
import type { AdminContentTeamPartialUpdate200Meta } from "./adminContentTeamPartialUpdate200Meta";

export type AdminContentTeamPartialUpdate200 = {
  data: TeamMember;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentTeamPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
