/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Lead } from "./lead";
import type { AdminBusinessLeadsStatusPartialUpdate200Meta } from "./adminBusinessLeadsStatusPartialUpdate200Meta";

export type AdminBusinessLeadsStatusPartialUpdate200 = {
  data: Lead;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessLeadsStatusPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
