/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MaintenanceLog } from "./maintenanceLog";
import type { AdminOperationsMaintenanceLogsRetrieve200Meta } from "./adminOperationsMaintenanceLogsRetrieve200Meta";

export type AdminOperationsMaintenanceLogsRetrieve200 = {
  data: MaintenanceLog;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMaintenanceLogsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
