/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Asset } from "./asset";
import type { AdminAssetsBlueprintsUploadCreate200Meta } from "./adminAssetsBlueprintsUploadCreate200Meta";

export type AdminAssetsBlueprintsUploadCreate200 = {
  data: Asset;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAssetsBlueprintsUploadCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
