/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityTimeline } from "./activityTimeline";
import type { AdminBusinessTimelineCreate201Meta } from "./adminBusinessTimelineCreate201Meta";

export type AdminBusinessTimelineCreate201 = {
  data: ActivityTimeline;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessTimelineCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
