/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContentResourcesListResourceType } from "./adminContentResourcesListResourceType";
import type { AdminContentResourcesListStatus } from "./adminContentResourcesListStatus";

export type AdminContentResourcesListParams = {
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * * `engineering-intelligence` - Engineering Intelligence
   * `blog` - Blog
   * `guide` - Guide
   * `technology-guide` - Technology Guide
   */
  resource_type?: AdminContentResourcesListResourceType;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `Draft` - Draft
   * `In Review` - In Review
   * `Approved` - Approved
   * `Scheduled` - Scheduled
   * `Published` - Published
   * `Archived` - Archived
   */
  status?: AdminContentResourcesListStatus;
};
