/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminConversationSession } from "./adminConversationSession";
import type { AdminOverviewRetrieve200Meta } from "./adminOverviewRetrieve200Meta";

export type AdminOverviewRetrieve200 = {
  data: AdminConversationSession;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOverviewRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
