/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedAdminConversationSessionList } from "./paginatedAdminConversationSessionList";
import type { AdminConversationsList200Meta } from "./adminConversationsList200Meta";

export type AdminConversationsList200 = {
  data: PaginatedAdminConversationSessionList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminConversationsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
