/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Portfolio } from "./portfolio";
import type { AdminContentPortfolioRetrieve200Meta } from "./adminContentPortfolioRetrieve200Meta";

export type AdminContentPortfolioRetrieve200 = {
  data: Portfolio;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentPortfolioRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
