/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminContentTestimonialsListTestimonialType =
  (typeof AdminContentTestimonialsListTestimonialType)[keyof typeof AdminContentTestimonialsListTestimonialType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminContentTestimonialsListTestimonialType = {
  Client: "Client",
  Employee: "Employee",
  Investor: "Investor",
  Mentor: "Mentor",
  Partner: "Partner",
} as const;
