/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminAssetsContractsListAccessLevel } from "./adminAssetsContractsListAccessLevel";
import type { AdminAssetsContractsListAssetType } from "./adminAssetsContractsListAssetType";

export type AdminAssetsContractsListParams = {
  /**
   * * `public` - Public
   * `private` - Private
   * `tenant_restricted` - Tenant Restricted
   */
  access_level?: AdminAssetsContractsListAccessLevel;
  /**
   * * `image` - Image
   * `video` - Video
   * `pdf_report` - PDF Report
   * `invoice` - Invoice
   * `contract` - Contract
   * `other` - Other
   */
  asset_type?: AdminAssetsContractsListAssetType;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * A search term.
   */
  search?: string;
  storage_provider?: string;
};
