/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionCodenames } from "./permissionCodenames";
import type { AdminRolesRemovePermissionsCreate200Meta } from "./adminRolesRemovePermissionsCreate200Meta";

export type AdminRolesRemovePermissionsCreate200 = {
  data: PermissionCodenames;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminRolesRemovePermissionsCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
