/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedPaymentList } from "./paginatedPaymentList";
import type { AdminBusinessPaymentsList200Meta } from "./adminBusinessPaymentsList200Meta";

export type AdminBusinessPaymentsList200 = {
  data: PaginatedPaymentList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessPaymentsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
