/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MaintenanceLog } from "./maintenanceLog";
import type { AdminOperationsMaintenanceLogsCreate201Meta } from "./adminOperationsMaintenanceLogsCreate201Meta";

export type AdminOperationsMaintenanceLogsCreate201 = {
  data: MaintenanceLog;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMaintenanceLogsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
