/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SupportTicket } from "./supportTicket";
import type { AdminOperationsSupportTicketsRetrieve200Meta } from "./adminOperationsSupportTicketsRetrieve200Meta";

export type AdminOperationsSupportTicketsRetrieve200 = {
  data: SupportTicket;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsSupportTicketsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
