/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Service } from "./service";
import type { AdminContentServicesRetrieve200Meta } from "./adminContentServicesRetrieve200Meta";

export type AdminContentServicesRetrieve200 = {
  data: Service;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentServicesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
