/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLeadStatusHistoryList } from "./paginatedLeadStatusHistoryList";
import type { AdminCrmLeadsStatusHistoryList200Meta } from "./adminCrmLeadsStatusHistoryList200Meta";

export type AdminCrmLeadsStatusHistoryList200 = {
  data: PaginatedLeadStatusHistoryList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminCrmLeadsStatusHistoryList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
