/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedProjectList } from "./paginatedProjectList";
import type { AdminBusinessProjectsList200Meta } from "./adminBusinessProjectsList200Meta";

export type AdminBusinessProjectsList200 = {
  data: PaginatedProjectList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessProjectsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
