/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedPlatformFeatureList } from "./paginatedPlatformFeatureList";
import type { AdminPlatformFeaturesList200Meta } from "./adminPlatformFeaturesList200Meta";

export type AdminPlatformFeaturesList200 = {
  data: PaginatedPlatformFeatureList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformFeaturesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
