/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedMaintenanceLogList } from "./paginatedMaintenanceLogList";
import type { AdminOperationsMaintenanceLogsList200Meta } from "./adminOperationsMaintenanceLogsList200Meta";

export type AdminOperationsMaintenanceLogsList200 = {
  data: PaginatedMaintenanceLogList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMaintenanceLogsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
