/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { FAQCategory } from "./fAQCategory";
import type { AdminContentFaqCategoriesCreate201Meta } from "./adminContentFaqCategoriesCreate201Meta";

export type AdminContentFaqCategoriesCreate201 = {
  data: FAQCategory;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentFaqCategoriesCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
