/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadDetail } from "./leadDetail";
import type { AdminLeadsRetrieve200Meta } from "./adminLeadsRetrieve200Meta";

export type AdminLeadsRetrieve200 = {
  data: LeadDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLeadsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
