/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KnowledgeEntryList } from "./knowledgeEntryList";
import type { AdminKbStatusRetrieve200Meta } from "./adminKbStatusRetrieve200Meta";

export type AdminKbStatusRetrieve200 = {
  data: KnowledgeEntryList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKbStatusRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
