/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Contact } from "./contact";
import type { AdminBusinessContactsBulkUpdateCreate200Meta } from "./adminBusinessContactsBulkUpdateCreate200Meta";

export type AdminBusinessContactsBulkUpdateCreate200 = {
  data: Contact;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessContactsBulkUpdateCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
