/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KnowledgeEntryVersionList } from "./knowledgeEntryVersionList";
import type { AdminKnowledgeEntriesVersionsList200Meta } from "./adminKnowledgeEntriesVersionsList200Meta";

export type AdminKnowledgeEntriesVersionsList200 = {
  data: KnowledgeEntryVersionList[];
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKnowledgeEntriesVersionsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
