/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminConversationsListQualificationState =
  (typeof AdminConversationsListQualificationState)[keyof typeof AdminConversationsListQualificationState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminConversationsListQualificationState = {
  disqualified: "disqualified",
  escalated_to_human: "escalated_to_human",
  gathering: "gathering",
  not_started: "not_started",
  qualified: "qualified",
} as const;
