/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedTimelineEventList } from "./paginatedTimelineEventList";
import type { AdminPlatformTimelineList200Meta } from "./adminPlatformTimelineList200Meta";

export type AdminPlatformTimelineList200 = {
  data: PaginatedTimelineEventList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformTimelineList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
