/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedIncidentList } from "./paginatedIncidentList";
import type { AdminOperationsIncidentsList200Meta } from "./adminOperationsIncidentsList200Meta";

export type AdminOperationsIncidentsList200 = {
  data: PaginatedIncidentList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsIncidentsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
