/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLog } from "./auditLog";
import type { AdminUsersAuditLogRetrieve200Meta } from "./adminUsersAuditLogRetrieve200Meta";

export type AdminUsersAuditLogRetrieve200 = {
  data: AuditLog;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminUsersAuditLogRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
