/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedPortfolioList } from "./paginatedPortfolioList";
import type { AdminContentPortfolioList200Meta } from "./adminContentPortfolioList200Meta";

export type AdminContentPortfolioList200 = {
  data: PaginatedPortfolioList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentPortfolioList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
