/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedUserListList } from "./paginatedUserListList";
import type { AdminUsersList200Meta } from "./adminUsersList200Meta";

export type AdminUsersList200 = {
  data: PaginatedUserListList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminUsersList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
