/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedIntegrationCredentialList } from "./paginatedIntegrationCredentialList";
import type { AdminIntegrationsCredentialsList200Meta } from "./adminIntegrationsCredentialsList200Meta";

export type AdminIntegrationsCredentialsList200 = {
  data: PaginatedIntegrationCredentialList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntegrationsCredentialsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
