/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MigrationRequest } from "./migrationRequest";
import type { AdminOperationsMigrationRequestsPartialUpdate200Meta } from "./adminOperationsMigrationRequestsPartialUpdate200Meta";

export type AdminOperationsMigrationRequestsPartialUpdate200 = {
  data: MigrationRequest;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMigrationRequestsPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
