/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Notification } from "./notification";
import type { AdminNotificationsRetrieve200Meta } from "./adminNotificationsRetrieve200Meta";

export type AdminNotificationsRetrieve200 = {
  data: Notification;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminNotificationsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
