/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Company } from "./company";
import type { AdminBusinessCompaniesBulkUpdateCreate200Meta } from "./adminBusinessCompaniesBulkUpdateCreate200Meta";

export type AdminBusinessCompaniesBulkUpdateCreate200 = {
  data: Company;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessCompaniesBulkUpdateCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
