/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Resource } from "./resource";
import type { AdminContentResourcesRetrieve200Meta } from "./adminContentResourcesRetrieve200Meta";

export type AdminContentResourcesRetrieve200 = {
  data: Resource;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentResourcesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
