/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminConversationsListStatus =
  (typeof AdminConversationsListStatus)[keyof typeof AdminConversationsListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminConversationsListStatus = {
  abandoned: "abandoned",
  active: "active",
  closed: "closed",
  escalated: "escalated",
  idle: "idle",
} as const;
