/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedSettingList } from "./paginatedSettingList";
import type { AdminSettingsList2200Meta } from "./adminSettingsList2200Meta";

export type AdminSettingsList2200 = {
  data: PaginatedSettingList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminSettingsList2200Meta;
  /** Always true for successful requests */
  success: boolean;
};
