/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Industry } from "./industry";
import type { AdminContentIndustriesRetrieve200Meta } from "./adminContentIndustriesRetrieve200Meta";

export type AdminContentIndustriesRetrieve200 = {
  data: Industry;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentIndustriesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
