/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminPlatformJobsListStatus =
  (typeof AdminPlatformJobsListStatus)[keyof typeof AdminPlatformJobsListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPlatformJobsListStatus = {
  FAILURE: "FAILURE",
  PENDING: "PENDING",
  REVOKED: "REVOKED",
  STARTED: "STARTED",
  SUCCESS: "SUCCESS",
} as const;
