/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SettingPublic } from "./settingPublic";
import type { AdminSettingsPublicList200Meta } from "./adminSettingsPublicList200Meta";

export type AdminSettingsPublicList200 = {
  data: SettingPublic[];
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminSettingsPublicList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
