/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLabToolList } from "./paginatedLabToolList";
import type { AdminLabToolsList200Meta } from "./adminLabToolsList200Meta";

export type AdminLabToolsList200 = {
  data: PaginatedLabToolList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabToolsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
