/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ResourceCategory } from "./resourceCategory";
import type { AdminContentResourceCategoriesPartialUpdate200Meta } from "./adminContentResourceCategoriesPartialUpdate200Meta";

export type AdminContentResourceCategoriesPartialUpdate200 = {
  data: ResourceCategory;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentResourceCategoriesPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
