/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminAssetsBlueprintsListAccessLevel =
  (typeof AdminAssetsBlueprintsListAccessLevel)[keyof typeof AdminAssetsBlueprintsListAccessLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminAssetsBlueprintsListAccessLevel = {
  private: "private",
  public: "public",
  tenant_restricted: "tenant_restricted",
} as const;
