/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ResetSettingsResponse } from "./resetSettingsResponse";
import type { AdminPlatformResetCreate200Meta } from "./adminPlatformResetCreate200Meta";

export type AdminPlatformResetCreate200 = {
  data: ResetSettingsResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformResetCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
