/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminContentTestimonialsListStatus } from "./adminContentTestimonialsListStatus";
import type { AdminContentTestimonialsListTestimonialType } from "./adminContentTestimonialsListTestimonialType";

export type AdminContentTestimonialsListParams = {
  is_featured?: boolean;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `Draft` - Draft
   * `In Review` - In Review
   * `Approved` - Approved
   * `Scheduled` - Scheduled
   * `Published` - Published
   * `Archived` - Archived
   */
  status?: AdminContentTestimonialsListStatus;
  /**
   * * `Client` - Client
   * `Partner` - Partner
   * `Investor` - Investor
   * `Mentor` - Mentor
   * `Employee` - Employee
   */
  testimonial_type?: AdminContentTestimonialsListTestimonialType;
};
