/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPlatformListGroup } from "./adminPlatformListGroup";
import type { AdminPlatformListValueType } from "./adminPlatformListValueType";

export type AdminPlatformListParams = {
  /**
   * * `GENERAL` - General
   * `AI` - AI
   * `CRM` - CRM
   * `KNOWLEDGE_BASE` - Knowledge Base
   * `ANALYTICS` - Analytics
   * `NOTIFICATIONS` - Notifications
   * `EMAIL` - Email
   * `SECURITY` - Security
   * `FEATURES` - Features
   * `APPEARANCE` - Appearance
   * `MAINTENANCE` - Maintenance
   */
  group?: AdminPlatformListGroup;
  is_editable?: boolean;
  is_public?: boolean;
  is_sensitive?: boolean;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `STRING` - String
   * `INTEGER` - Integer
   * `BOOLEAN` - Boolean
   * `FLOAT` - Float
   * `JSON` - JSON
   * `EMAIL` - Email
   * `URL` - URL
   */
  value_type?: AdminPlatformListValueType;
};
