/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { CRMDashboard } from "./cRMDashboard";
import type { AdminCrmDashboardRetrieve200Meta } from "./adminCrmDashboardRetrieve200Meta";

export type AdminCrmDashboardRetrieve200 = {
  data: CRMDashboard;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminCrmDashboardRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
