/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedRoleListList } from "./paginatedRoleListList";
import type { AdminRolesList200Meta } from "./adminRolesList200Meta";

export type AdminRolesList200 = {
  data: PaginatedRoleListList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminRolesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
