/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedConsultationList } from "./paginatedConsultationList";
import type { AdminBusinessConsultationsList200Meta } from "./adminBusinessConsultationsList200Meta";

export type AdminBusinessConsultationsList200 = {
  data: PaginatedConsultationList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessConsultationsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
