/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedPartnershipList } from "./paginatedPartnershipList";
import type { AdminContentPartnershipsList200Meta } from "./adminContentPartnershipsList200Meta";

export type AdminContentPartnershipsList200 = {
  data: PaginatedPartnershipList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentPartnershipsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
