/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLabWorkspaceList } from "./paginatedLabWorkspaceList";
import type { AdminLabWorkspacesList200Meta } from "./adminLabWorkspacesList200Meta";

export type AdminLabWorkspacesList200 = {
  data: PaginatedLabWorkspaceList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabWorkspacesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
