/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { _UnreadCountResponse } from "./_unreadCountResponse";
import type { AdminNotificationsUnreadCountRetrieve200Meta } from "./adminNotificationsUnreadCountRetrieve200Meta";

export type AdminNotificationsUnreadCountRetrieve200 = {
  data: _UnreadCountResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminNotificationsUnreadCountRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
