/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RatingEnum } from "./ratingEnum";

export interface AdminFeedback {
  /** @nullable */
  comment?: string | null;
  readonly created_at: string;
  readonly id: string;
  /** @nullable */
  message?: number | null;
  rating: RatingEnum;
  session: string;
}
