/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedNotificationList } from "./paginatedNotificationList";
import type { AdminNotificationsList200Meta } from "./adminNotificationsList200Meta";

export type AdminNotificationsList200 = {
  data: PaginatedNotificationList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminNotificationsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
