/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { IntegrationCredential } from "./integrationCredential";
import type { AdminIntegrationsCredentialsCreate201Meta } from "./adminIntegrationsCredentialsCreate201Meta";

export type AdminIntegrationsCredentialsCreate201 = {
  data: IntegrationCredential;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntegrationsCredentialsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
