/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadNote } from "./leadNote";
import type { AdminLeadsNotesCreate201Meta } from "./adminLeadsNotesCreate201Meta";

export type AdminLeadsNotesCreate201 = {
  data: LeadNote;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLeadsNotesCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
