/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarSlot } from "./calendarSlot";
import type { AdminEngagementCalendarRetrieve200Meta } from "./adminEngagementCalendarRetrieve200Meta";

export type AdminEngagementCalendarRetrieve200 = {
  data: CalendarSlot;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementCalendarRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
