/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLeadNoteList } from "./paginatedLeadNoteList";
import type { AdminLeadsNotesList200Meta } from "./adminLeadsNotesList200Meta";

export type AdminLeadsNotesList200 = {
  data: PaginatedLeadNoteList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLeadsNotesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
