/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminOperationsIncidentsListSeverity =
  (typeof AdminOperationsIncidentsListSeverity)[keyof typeof AdminOperationsIncidentsListSeverity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOperationsIncidentsListSeverity = {
  Critical: "Critical",
  Major: "Major",
  Minor: "Minor",
} as const;
