/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Portfolio } from "./portfolio";
import type { AdminContentPortfolioPartialUpdate200Meta } from "./adminContentPortfolioPartialUpdate200Meta";

export type AdminContentPortfolioPartialUpdate200 = {
  data: Portfolio;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentPortfolioPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
