/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SettingsGroupResponse } from "./settingsGroupResponse";
import type { AdminPlatformGroupsList200Meta } from "./adminPlatformGroupsList200Meta";

export type AdminPlatformGroupsList200 = {
  data: SettingsGroupResponse[];
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformGroupsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
