/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TechnologyPartnership } from "./technologyPartnership";
import type { AdminBusinessPartnershipsCreate201Meta } from "./adminBusinessPartnershipsCreate201Meta";

export type AdminBusinessPartnershipsCreate201 = {
  data: TechnologyPartnership;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessPartnershipsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
