/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Contract } from "./contract";
import type { AdminBusinessContractsBulkUpdateCreate200Meta } from "./adminBusinessContractsBulkUpdateCreate200Meta";

export type AdminBusinessContractsBulkUpdateCreate200 = {
  data: Contract;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessContractsBulkUpdateCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
