/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KnowledgeEntryDetail } from "./knowledgeEntryDetail";
import type { AdminKnowledgeEntriesCreate201Meta } from "./adminKnowledgeEntriesCreate201Meta";

export type AdminKnowledgeEntriesCreate201 = {
  data: KnowledgeEntryDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKnowledgeEntriesCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
