/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EngineeringLabTool } from "./engineeringLabTool";
import type { AdminContentLabToolsCreate201Meta } from "./adminContentLabToolsCreate201Meta";

export type AdminContentLabToolsCreate201 = {
  data: EngineeringLabTool;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentLabToolsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
