/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Asset } from "./asset";
import type { AdminAssetsReportsCreate201Meta } from "./adminAssetsReportsCreate201Meta";

export type AdminAssetsReportsCreate201 = {
  data: Asset;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAssetsReportsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
