/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Consultation } from "./consultation";
import type { AdminBusinessConsultationsUpdate200Meta } from "./adminBusinessConsultationsUpdate200Meta";

export type AdminBusinessConsultationsUpdate200 = {
  data: Consultation;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessConsultationsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
