/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AIConsultantPersona } from "./aIConsultantPersona";
import type { AdminContentAiPersonasUpdate200Meta } from "./adminContentAiPersonasUpdate200Meta";

export type AdminContentAiPersonasUpdate200 = {
  data: AIConsultantPersona;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentAiPersonasUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
