/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminKbEntriesListParams = {
  /**
   * Filter by category slug
   */
  category?: string;
  /**
   * Order by field
   */
  ordering?: string;
  /**
   * Full-text search
   */
  search?: string;
  /**
   * Filter by status: draft, published, archived
   */
  status?: string;
};
