/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedAssetList } from "./paginatedAssetList";
import type { AdminAssetsMediaList200Meta } from "./adminAssetsMediaList200Meta";

export type AdminAssetsMediaList200 = {
  data: PaginatedAssetList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAssetsMediaList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
