/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { _MarkedReadResponse } from "./_markedReadResponse";
import type { AdminNotificationsReadAllPartialUpdate200Meta } from "./adminNotificationsReadAllPartialUpdate200Meta";

export type AdminNotificationsReadAllPartialUpdate200 = {
  data: _MarkedReadResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminNotificationsReadAllPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
