/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminEngagementSessionsListStatus } from "./adminEngagementSessionsListStatus";

export type AdminEngagementSessionsListParams = {
  /**
   * Unique identifier for this record.
   */
  consultation_type?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `Pending` - Pending
   * `Booked` - Booked
   * `Completed` - Completed
   * `Cancelled` - Cancelled
   */
  status?: AdminEngagementSessionsListStatus;
};
