/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedBackgroundJobList } from "./paginatedBackgroundJobList";
import type { AdminPlatformJobsList200Meta } from "./adminPlatformJobsList200Meta";

export type AdminPlatformJobsList200 = {
  data: PaginatedBackgroundJobList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformJobsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
