/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedProjectHealthList } from "./paginatedProjectHealthList";
import type { AdminOperationsProjectHealthList200Meta } from "./adminOperationsProjectHealthList200Meta";

export type AdminOperationsProjectHealthList200 = {
  data: PaginatedProjectHealthList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsProjectHealthList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
