/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Proposal } from "./proposal";
import type { AdminBusinessProposalsCreate201Meta } from "./adminBusinessProposalsCreate201Meta";

export type AdminBusinessProposalsCreate201 = {
  data: Proposal;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessProposalsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
