/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { NavigationItem } from "./navigationItem";
import type { AdminContentNavigationUpdate200Meta } from "./adminContentNavigationUpdate200Meta";

export type AdminContentNavigationUpdate200 = {
  data: NavigationItem;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentNavigationUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
