/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LabWorkspace } from "./labWorkspace";
import type { AdminLabWorkspacesPartialUpdate200Meta } from "./adminLabWorkspacesPartialUpdate200Meta";

export type AdminLabWorkspacesPartialUpdate200 = {
  data: LabWorkspace;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabWorkspacesPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
