/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MaintenancePlan } from "./maintenancePlan";
import type { AdminOperationsMaintenancePlansUpdate200Meta } from "./adminOperationsMaintenancePlansUpdate200Meta";

export type AdminOperationsMaintenancePlansUpdate200 = {
  data: MaintenancePlan;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMaintenancePlansUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
