/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLeadFollowUpList } from "./paginatedLeadFollowUpList";
import type { AdminCrmFollowupsPendingList200Meta } from "./adminCrmFollowupsPendingList200Meta";

export type AdminCrmFollowupsPendingList200 = {
  data: PaginatedLeadFollowUpList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminCrmFollowupsPendingList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
