/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminBusinessProjectsListStatus =
  (typeof AdminBusinessProjectsListStatus)[keyof typeof AdminBusinessProjectsListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminBusinessProjectsListStatus = {
  Completed: "Completed",
  Deployment: "Deployment",
  Development: "Development",
  Onboarding: "Onboarding",
  Planning: "Planning",
  QA: "QA",
} as const;
