/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminIntelligenceMessagesListRole } from "./adminIntelligenceMessagesListRole";

export type AdminIntelligenceMessagesListParams = {
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * * `user` - User
   * `assistant` - Assistant
   * `system` - System
   */
  role?: AdminIntelligenceMessagesListRole;
  /**
   * A search term.
   */
  search?: string;
  /**
   * Unique identifier for this record.
   */
  session?: string;
};
