/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LabTool } from "./labTool";
import type { AdminLabToolsRetrieve200Meta } from "./adminLabToolsRetrieve200Meta";

export type AdminLabToolsRetrieve200 = {
  data: LabTool;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabToolsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
