/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TeamMember } from "./teamMember";
import type { AdminContentTeamUpdate200Meta } from "./adminContentTeamUpdate200Meta";

export type AdminContentTeamUpdate200 = {
  data: TeamMember;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentTeamUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
