/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminConversationsListEscalationStatus } from "./adminConversationsListEscalationStatus";
import type { AdminConversationsListQualificationState } from "./adminConversationsListQualificationState";
import type { AdminConversationsListStatus } from "./adminConversationsListStatus";

export type AdminConversationsListParams = {
  /**
   * * `none` - None
   * `pending` - Pending
   * `assigned` - Assigned
   * `in_progress` - In Progress
   * `resolved` - Resolved
   * `closed` - Closed
   */
  escalation_status?: AdminConversationsListEscalationStatus;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  /**
   * * `not_started` - Not Started
   * `gathering` - Gathering
   * `qualified` - Qualified
   * `disqualified` - Disqualified
   * `escalated_to_human` - Escalated To Human
   */
  qualification_state?: AdminConversationsListQualificationState;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `active` - Active
   * `idle` - Idle
   * `closed` - Closed
   * `escalated` - Escalated
   * `abandoned` - Abandoned
   */
  status?: AdminConversationsListStatus;
};
