/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminUsersListParams = {
  /**
   * Filter: date_joined >= value (ISO 8601)
   */
  date_joined_after?: string;
  /**
   * Filter: date_joined <= value (ISO 8601)
   */
  date_joined_before?: string;
  /**
   * Filter by group name
   */
  group?: string;
  /**
   * Filter by active status
   */
  is_active?: boolean;
  /**
   * Filter by staff status
   */
  is_staff?: boolean;
  /**
   * Filter by superuser status
   */
  is_superuser?: boolean;
  /**
   * Filter: last_login >= value (ISO 8601)
   */
  last_login_after?: string;
  /**
   * Filter: last_login <= value (ISO 8601)
   */
  last_login_before?: string;
  /**
   * Order by: username, email, date_joined, last_login, first_name, last_name (prefix with - for desc)
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  /**
   * Search across username, email, first_name, last_name
   */
  search?: string;
};
