/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedServiceList } from "./paginatedServiceList";
import type { AdminContentServicesList200Meta } from "./adminContentServicesList200Meta";

export type AdminContentServicesList200 = {
  data: PaginatedServiceList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentServicesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
