/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedSupportTicketList } from "./paginatedSupportTicketList";
import type { AdminOperationsSupportTicketsList200Meta } from "./adminOperationsSupportTicketsList200Meta";

export type AdminOperationsSupportTicketsList200 = {
  data: PaginatedSupportTicketList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsSupportTicketsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
