/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Recommendation } from "./recommendation";
import type { AdminIntelligenceRecommendationsPartialUpdate200Meta } from "./adminIntelligenceRecommendationsPartialUpdate200Meta";

export type AdminIntelligenceRecommendationsPartialUpdate200 = {
  data: Recommendation;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceRecommendationsPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
