/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadAnalyticsResponse } from "./leadAnalyticsResponse";
import type { AdminAnalyticsLeadsRetrieve200Meta } from "./adminAnalyticsLeadsRetrieve200Meta";

export type AdminAnalyticsLeadsRetrieve200 = {
  data: LeadAnalyticsResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAnalyticsLeadsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
