/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminPlatformJobsListStatus } from "./adminPlatformJobsListStatus";

export type AdminPlatformJobsListParams = {
  name?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Number of results to return per page.
   */
  page_size?: number;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `PENDING` - Pending
   * `STARTED` - Started
   * `SUCCESS` - Success
   * `FAILURE` - Failure
   * `REVOKED` - Revoked
   */
  status?: AdminPlatformJobsListStatus;
};
