/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationType } from "./consultationType";
import type { AdminEngagementTypesPartialUpdate200Meta } from "./adminEngagementTypesPartialUpdate200Meta";

export type AdminEngagementTypesPartialUpdate200 = {
  data: ConsultationType;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementTypesPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
