/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Lead } from "./lead";
import type { AdminBusinessLeadsCreate201Meta } from "./adminBusinessLeadsCreate201Meta";

export type AdminBusinessLeadsCreate201 = {
  data: Lead;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessLeadsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
