/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Project } from "./project";
import type { AdminBusinessProjectsBulkUpdateCreate200Meta } from "./adminBusinessProjectsBulkUpdateCreate200Meta";

export type AdminBusinessProjectsBulkUpdateCreate200 = {
  data: Project;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessProjectsBulkUpdateCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
