/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedEngineeringLabToolList } from "./paginatedEngineeringLabToolList";
import type { AdminContentLabToolsList200Meta } from "./adminContentLabToolsList200Meta";

export type AdminContentLabToolsList200 = {
  data: PaginatedEngineeringLabToolList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentLabToolsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
