/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LabTool } from "./labTool";
import type { AdminLabToolsCreate201Meta } from "./adminLabToolsCreate201Meta";

export type AdminLabToolsCreate201 = {
  data: LabTool;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabToolsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
