/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleUser } from "./roleUser";
import type { AdminRolesUsersRetrieve200Meta } from "./adminRolesUsersRetrieve200Meta";

export type AdminRolesUsersRetrieve200 = {
  data: RoleUser;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminRolesUsersRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
