/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformFeature } from "./platformFeature";
import type { AdminPlatformFeaturesCreate201Meta } from "./adminPlatformFeaturesCreate201Meta";

export type AdminPlatformFeaturesCreate201 = {
  data: PlatformFeature;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformFeaturesCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
