/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminBusinessPaymentsListStatus } from "./adminBusinessPaymentsListStatus";

export type AdminBusinessPaymentsListParams = {
  /**
   * Unique identifier for this record.
   */
  company?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * Unique identifier for this record.
   */
  project?: string;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `Pending` - Pending
   * `Paid` - Paid
   * `Failed` - Failed
   */
  status?: AdminBusinessPaymentsListStatus;
};
