/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PartnershipModel } from "./partnershipModel";
import type { AdminEngagementPartnershipsCreate201Meta } from "./adminEngagementPartnershipsCreate201Meta";

export type AdminEngagementPartnershipsCreate201 = {
  data: PartnershipModel;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementPartnershipsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
