/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedMigrationRequestList } from "./paginatedMigrationRequestList";
import type { AdminOperationsMigrationRequestsList200Meta } from "./adminOperationsMigrationRequestsList200Meta";

export type AdminOperationsMigrationRequestsList200 = {
  data: PaginatedMigrationRequestList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMigrationRequestsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
