/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemHealth } from "./systemHealth";
import type { AdminOperationsSystemHealthPartialUpdate200Meta } from "./adminOperationsSystemHealthPartialUpdate200Meta";

export type AdminOperationsSystemHealthPartialUpdate200 = {
  data: SystemHealth;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsSystemHealthPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
