/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLeadActivityList } from "./paginatedLeadActivityList";
import type { AdminCrmLeadsActivitiesList200Meta } from "./adminCrmLeadsActivitiesList200Meta";

export type AdminCrmLeadsActivitiesList200 = {
  data: PaginatedLeadActivityList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminCrmLeadsActivitiesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
