/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadFollowUp } from "./leadFollowUp";
import type { AdminCrmFollowupsUpdate200Meta } from "./adminCrmFollowupsUpdate200Meta";

export type AdminCrmFollowupsUpdate200 = {
  data: LeadFollowUp;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminCrmFollowupsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
