/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadUpdate } from "./leadUpdate";
import type { AdminLeadsUpdate200Meta } from "./adminLeadsUpdate200Meta";

export type AdminLeadsUpdate200 = {
  data: LeadUpdate;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLeadsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
