/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { OverviewResponse } from "./overviewResponse";
import type { AdminAnalyticsOverviewRetrieve200Meta } from "./adminAnalyticsOverviewRetrieve200Meta";

export type AdminAnalyticsOverviewRetrieve200 = {
  data: OverviewResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAnalyticsOverviewRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
