/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceCategory } from "./serviceCategory";
import type { AdminContentServiceCategoriesCreate201Meta } from "./adminContentServiceCategoriesCreate201Meta";

export type AdminContentServiceCategoriesCreate201 = {
  data: ServiceCategory;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentServiceCategoriesCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
