/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedChatMessageList } from "./paginatedChatMessageList";
import type { AdminIntelligenceMessagesList200Meta } from "./adminIntelligenceMessagesList200Meta";

export type AdminIntelligenceMessagesList200 = {
  data: PaginatedChatMessageList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceMessagesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
