/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminOperationsMigrationRequestsListStatus =
  (typeof AdminOperationsMigrationRequestsListStatus)[keyof typeof AdminOperationsMigrationRequestsListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOperationsMigrationRequestsListStatus = {
  Completed: "Completed",
  Failed: "Failed",
  In_Progress: "In Progress",
  Pending: "Pending",
} as const;
