/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from "./category";
import type { AdminKbCategoriesPartialUpdate200Meta } from "./adminKbCategoriesPartialUpdate200Meta";

export type AdminKbCategoriesPartialUpdate200 = {
  data: Category;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKbCategoriesPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
