/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminOperationsSystemHealthListStatus } from "./adminOperationsSystemHealthListStatus";

export type AdminOperationsSystemHealthListParams = {
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * A search term.
   */
  search?: string;
  /**
   * * `Operational` - Operational
   * `Degraded` - Degraded
   * `Down` - Down
   */
  status?: AdminOperationsSystemHealthListStatus;
};
