/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MaintenancePlan } from "./maintenancePlan";
import type { AdminBusinessMaintenanceCreate201Meta } from "./adminBusinessMaintenanceCreate201Meta";

export type AdminBusinessMaintenanceCreate201 = {
  data: MaintenancePlan;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessMaintenanceCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
