/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedServiceCategoryList } from "./paginatedServiceCategoryList";
import type { AdminContentServiceCategoriesList200Meta } from "./adminContentServiceCategoriesList200Meta";

export type AdminContentServiceCategoriesList200 = {
  data: PaginatedServiceCategoryList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentServiceCategoriesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
