/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminPlatformAuditLogsListParams = {
  action?: string;
  /**
   * Unique identifier for this record.
   */
  actor?: string;
  content_type?: number;
  /**
   * The pagination cursor value.
   */
  cursor?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A search term.
   */
  search?: string;
};
