/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { BulkAction } from "./bulkAction";
import type { AdminUsersBulkDeactivateCreate200Meta } from "./adminUsersBulkDeactivateCreate200Meta";

export type AdminUsersBulkDeactivateCreate200 = {
  data: BulkAction;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminUsersBulkDeactivateCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
