/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLabReportList } from "./paginatedLabReportList";
import type { AdminLabReportsList200Meta } from "./adminLabReportsList200Meta";

export type AdminLabReportsList200 = {
  data: PaginatedLabReportList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabReportsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
