/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { GlobalSearchResult } from "./globalSearchResult";
import type { AdminSearchList200Meta } from "./adminSearchList200Meta";

export type AdminSearchList200 = {
  data: GlobalSearchResult[];
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminSearchList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
