/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LabReport } from "./labReport";
import type { AdminLabReportsUpdate200Meta } from "./adminLabReportsUpdate200Meta";

export type AdminLabReportsUpdate200 = {
  data: LabReport;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabReportsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
