/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Lead } from "./lead";
import type { AdminBusinessLeadKanbanList200Meta } from "./adminBusinessLeadKanbanList200Meta";

export type AdminBusinessLeadKanbanList200 = {
  data: Lead[];
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessLeadKanbanList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
