/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleCreate } from "./roleCreate";
import type { AdminRolesCreate201Meta } from "./adminRolesCreate201Meta";

export type AdminRolesCreate201 = {
  data: RoleCreate;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminRolesCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
