/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedConversationSessionList } from "./paginatedConversationSessionList";
import type { AdminIntelligenceConversationsList200Meta } from "./adminIntelligenceConversationsList200Meta";

export type AdminIntelligenceConversationsList200 = {
  data: PaginatedConversationSessionList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceConversationsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
