/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectHealth } from "./projectHealth";
import type { AdminOperationsProjectHealthPartialUpdate200Meta } from "./adminOperationsProjectHealthPartialUpdate200Meta";

export type AdminOperationsProjectHealthPartialUpdate200 = {
  data: ProjectHealth;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsProjectHealthPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
