/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedLeadList } from "./paginatedLeadList";
import type { AdminBusinessLeadsList200Meta } from "./adminBusinessLeadsList200Meta";

export type AdminBusinessLeadsList200 = {
  data: PaginatedLeadList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessLeadsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
