/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationSession } from "./consultationSession";
import type { AdminEngagementSessionsCreate201Meta } from "./adminEngagementSessionsCreate201Meta";

export type AdminEngagementSessionsCreate201 = {
  data: ConsultationSession;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementSessionsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
