/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminAssetsReportsListAccessLevel =
  (typeof AdminAssetsReportsListAccessLevel)[keyof typeof AdminAssetsReportsListAccessLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminAssetsReportsListAccessLevel = {
  private: "private",
  public: "public",
  tenant_restricted: "tenant_restricted",
} as const;
