/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCalendarSlotList } from "./paginatedCalendarSlotList";
import type { AdminEngagementCalendarList200Meta } from "./adminEngagementCalendarList200Meta";

export type AdminEngagementCalendarList200 = {
  data: PaginatedCalendarSlotList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementCalendarList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
