/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Tag } from "./tag";
import type { AdminKnowledgeTagsPartialUpdate200Meta } from "./adminKnowledgeTagsPartialUpdate200Meta";

export type AdminKnowledgeTagsPartialUpdate200 = {
  data: Tag;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKnowledgeTagsPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
