/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminContentLabToolsListStatus =
  (typeof AdminContentLabToolsListStatus)[keyof typeof AdminContentLabToolsListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminContentLabToolsListStatus = {
  Approved: "Approved",
  Archived: "Archived",
  Draft: "Draft",
  In_Review: "In Review",
  Published: "Published",
  Scheduled: "Scheduled",
} as const;
