/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationReport } from "./consultationReport";
import type { AdminEngagementReportsUpdate200Meta } from "./adminEngagementReportsUpdate200Meta";

export type AdminEngagementReportsUpdate200 = {
  data: ConsultationReport;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementReportsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
