/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { CacheResponse } from "./cacheResponse";
import type { AdminPlatformCacheRefreshCreate200Meta } from "./adminPlatformCacheRefreshCreate200Meta";

export type AdminPlatformCacheRefreshCreate200 = {
  data: CacheResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformCacheRefreshCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
