/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { CrmAnalyticsResponse } from "./crmAnalyticsResponse";
import type { AdminAnalyticsCrmRetrieve200Meta } from "./adminAnalyticsCrmRetrieve200Meta";

export type AdminAnalyticsCrmRetrieve200 = {
  data: CrmAnalyticsResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAnalyticsCrmRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
