/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedTagList } from "./paginatedTagList";
import type { AdminKbTagsList200Meta } from "./adminKbTagsList200Meta";

export type AdminKbTagsList200 = {
  data: PaginatedTagList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKbTagsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
