/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadAssignment } from "./leadAssignment";
import type { AdminLeadsAssignUpdate200Meta } from "./adminLeadsAssignUpdate200Meta";

export type AdminLeadsAssignUpdate200 = {
  data: LeadAssignment;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLeadsAssignUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
