/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { UserAnalyticsResponse } from "./userAnalyticsResponse";
import type { AdminAnalyticsUsersRetrieve200Meta } from "./adminAnalyticsUsersRetrieve200Meta";

export type AdminAnalyticsUsersRetrieve200 = {
  data: UserAnalyticsResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAnalyticsUsersRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
