/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SEOMetadata } from "./sEOMetadata";
import type { AdminContentSeoCreate201Meta } from "./adminContentSeoCreate201Meta";

export type AdminContentSeoCreate201 = {
  data: SEOMetadata;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentSeoCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
