/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCategoryList } from "./paginatedCategoryList";
import type { AdminKbCategoriesList200Meta } from "./adminKbCategoriesList200Meta";

export type AdminKbCategoriesList200 = {
  data: PaginatedCategoryList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKbCategoriesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
