/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminContentResourcesListResourceType =
  (typeof AdminContentResourcesListResourceType)[keyof typeof AdminContentResourcesListResourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminContentResourcesListResourceType = {
  blog: "blog",
  "engineering-intelligence": "engineering-intelligence",
  guide: "guide",
  "technology-guide": "technology-guide",
} as const;
