/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedTechnologyPartnershipList } from "./paginatedTechnologyPartnershipList";
import type { AdminBusinessPartnershipsList200Meta } from "./adminBusinessPartnershipsList200Meta";

export type AdminBusinessPartnershipsList200 = {
  data: PaginatedTechnologyPartnershipList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessPartnershipsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
