/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Tag } from "./tag";
import type { AdminKnowledgeTagsCreate201Meta } from "./adminKnowledgeTagsCreate201Meta";

export type AdminKnowledgeTagsCreate201 = {
  data: Tag;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKnowledgeTagsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
