/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Contract } from "./contract";
import type { AdminBusinessContractsCreate201Meta } from "./adminBusinessContractsCreate201Meta";

export type AdminBusinessContractsCreate201 = {
  data: Contract;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessContractsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
