/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Incident } from "./incident";
import type { AdminOperationsIncidentsUpdate200Meta } from "./adminOperationsIncidentsUpdate200Meta";

export type AdminOperationsIncidentsUpdate200 = {
  data: Incident;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsIncidentsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
