/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { UserCreate } from "./userCreate";
import type { AdminUsersCreate201Meta } from "./adminUsersCreate201Meta";

export type AdminUsersCreate201 = {
  data: UserCreate;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminUsersCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
