/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminConversationSessionDetail } from "./adminConversationSessionDetail";
import type { AdminConversationsRetrieve200Meta } from "./adminConversationsRetrieve200Meta";

export type AdminConversationsRetrieve200 = {
  data: AdminConversationSessionDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminConversationsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
