/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Proposal } from "./proposal";
import type { AdminBusinessProposalsUpdate200Meta } from "./adminBusinessProposalsUpdate200Meta";

export type AdminBusinessProposalsUpdate200 = {
  data: Proposal;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessProposalsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
