/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SEOMetadata } from "./sEOMetadata";
import type { AdminContentSeoRetrieve200Meta } from "./adminContentSeoRetrieve200Meta";

export type AdminContentSeoRetrieve200 = {
  data: SEOMetadata;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentSeoRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
