/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { VisitorIntelligenceProfile } from "./visitorIntelligenceProfile";
import type { AdminIntelligenceProfilesPartialUpdate200Meta } from "./adminIntelligenceProfilesPartialUpdate200Meta";

export type AdminIntelligenceProfilesPartialUpdate200 = {
  data: VisitorIntelligenceProfile;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceProfilesPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
