/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedContractList } from "./paginatedContractList";
import type { AdminBusinessContractsList200Meta } from "./adminBusinessContractsList200Meta";

export type AdminBusinessContractsList200 = {
  data: PaginatedContractList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessContractsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
