/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Asset } from "./asset";
import type { AdminAssetsContractsUploadCreate200Meta } from "./adminAssetsContractsUploadCreate200Meta";

export type AdminAssetsContractsUploadCreate200 = {
  data: Asset;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminAssetsContractsUploadCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
