/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationType } from "./consultationType";
import type { AdminEngagementTypesRetrieve200Meta } from "./adminEngagementTypesRetrieve200Meta";

export type AdminEngagementTypesRetrieve200 = {
  data: ConsultationType;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementTypesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
