/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ChannelEnum } from "./channelEnum";
import type { EscalationStatusEnum } from "./escalationStatusEnum";
import type { AdminFeedback } from "./adminFeedback";
import type { AdminMessage } from "./adminMessage";
import type { QualificationStateEnum } from "./qualificationStateEnum";
import type { Status088Enum } from "./status088Enum";

export interface AdminConversationSessionDetail {
  channel?: ChannelEnum;
  /** @nullable */
  closed_at?: string | null;
  readonly created_at: string;
  /** @nullable */
  deleted_at?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  detected_intent?: string | null;
  /** @nullable */
  escalated_at?: string | null;
  escalation_status?: EscalationStatusEnum;
  readonly feedback: readonly AdminFeedback[];
  readonly id: string;
  is_active?: boolean;
  is_deleted?: boolean;
  readonly last_message_at: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  lead_score?: number;
  /**
   * @maxLength 20
   * @nullable
   */
  locale?: string | null;
  readonly messages: readonly AdminMessage[];
  metadata?: string;
  /** @nullable */
  operator_notes?: string | null;
  qualification_state?: QualificationStateEnum;
  session_id?: string;
  status?: Status088Enum;
  readonly updated_at: string;
}
