/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { APIRequestLog } from "./aPIRequestLog";
import type { AdminIntegrationsLogsRetrieve200Meta } from "./adminIntegrationsLogsRetrieve200Meta";

export type AdminIntegrationsLogsRetrieve200 = {
  data: APIRequestLog;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntegrationsLogsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
