/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { FAQCategory } from "./fAQCategory";
import type { AdminContentFaqCategoriesRetrieve200Meta } from "./adminContentFaqCategoriesRetrieve200Meta";

export type AdminContentFaqCategoriesRetrieve200 = {
  data: FAQCategory;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentFaqCategoriesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
