/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemHealth } from "./systemHealth";
import type { AdminOperationsSystemHealthCreate201Meta } from "./adminOperationsSystemHealthCreate201Meta";

export type AdminOperationsSystemHealthCreate201 = {
  data: SystemHealth;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsSystemHealthCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
