/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedMaintenancePlanList } from "./paginatedMaintenancePlanList";
import type { AdminOperationsMaintenancePlansList200Meta } from "./adminOperationsMaintenancePlansList200Meta";

export type AdminOperationsMaintenancePlansList200 = {
  data: PaginatedMaintenancePlanList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsMaintenancePlansList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
