/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminBusinessLeadsListStatus =
  (typeof AdminBusinessLeadsListStatus)[keyof typeof AdminBusinessLeadsListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminBusinessLeadsListStatus = {
  Lost: "Lost",
  Negotiation: "Negotiation",
  New: "New",
  Proposal: "Proposal",
  Qualified: "Qualified",
  Won: "Won",
} as const;
