/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedConsultationSessionList } from "./paginatedConsultationSessionList";
import type { AdminEngagementSessionsList200Meta } from "./adminEngagementSessionsList200Meta";

export type AdminEngagementSessionsList200 = {
  data: PaginatedConsultationSessionList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminEngagementSessionsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
