/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KnowledgeEntryDetail } from "./knowledgeEntryDetail";
import type { AdminKbEntriesRestoreCreate200Meta } from "./adminKbEntriesRestoreCreate200Meta";

export type AdminKbEntriesRestoreCreate200 = {
  data: KnowledgeEntryDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminKbEntriesRestoreCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
