/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { BackgroundJob } from "./backgroundJob";
import type { AdminPlatformJobsRetrieve200Meta } from "./adminPlatformJobsRetrieve200Meta";

export type AdminPlatformJobsRetrieve200 = {
  data: BackgroundJob;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformJobsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
