/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleDetail } from "./roleDetail";
import type { AdminRolesRetrieve200Meta } from "./adminRolesRetrieve200Meta";

export type AdminRolesRetrieve200 = {
  data: RoleDetail;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminRolesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
