/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedIndustryList } from "./paginatedIndustryList";
import type { AdminContentIndustriesList200Meta } from "./adminContentIndustriesList200Meta";

export type AdminContentIndustriesList200 = {
  data: PaginatedIndustryList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentIndustriesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
