/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedSystemHealthList } from "./paginatedSystemHealthList";
import type { AdminOperationsSystemHealthList200Meta } from "./adminOperationsSystemHealthList200Meta";

export type AdminOperationsSystemHealthList200 = {
  data: PaginatedSystemHealthList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminOperationsSystemHealthList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
