/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminAssetsContractsListAssetType =
  (typeof AdminAssetsContractsListAssetType)[keyof typeof AdminAssetsContractsListAssetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminAssetsContractsListAssetType = {
  contract: "contract",
  image: "image",
  invoice: "invoice",
  other: "other",
  pdf_report: "pdf_report",
  video: "video",
} as const;
