/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Partnership } from "./partnership";
import type { AdminContentPartnershipsPartialUpdate200Meta } from "./adminContentPartnershipsPartialUpdate200Meta";

export type AdminContentPartnershipsPartialUpdate200 = {
  data: Partnership;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentPartnershipsPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
