/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Testimonial } from "./testimonial";
import type { AdminContentTestimonialsCreate201Meta } from "./adminContentTestimonialsCreate201Meta";

export type AdminContentTestimonialsCreate201 = {
  data: Testimonial;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentTestimonialsCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
