/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminPlatformListGroup =
  (typeof AdminPlatformListGroup)[keyof typeof AdminPlatformListGroup];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPlatformListGroup = {
  AI: "AI",
  ANALYTICS: "ANALYTICS",
  APPEARANCE: "APPEARANCE",
  CRM: "CRM",
  EMAIL: "EMAIL",
  FEATURES: "FEATURES",
  GENERAL: "GENERAL",
  KNOWLEDGE_BASE: "KNOWLEDGE_BASE",
  MAINTENANCE: "MAINTENANCE",
  NOTIFICATIONS: "NOTIFICATIONS",
  SECURITY: "SECURITY",
} as const;
