/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedPlatformSettingList } from "./paginatedPlatformSettingList";
import type { AdminPlatformList2200Meta } from "./adminPlatformList2200Meta";

export type AdminPlatformList2200 = {
  data: PaginatedPlatformSettingList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPlatformList2200Meta;
  /** Always true for successful requests */
  success: boolean;
};
