/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminPlatformListValueType =
  (typeof AdminPlatformListValueType)[keyof typeof AdminPlatformListValueType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminPlatformListValueType = {
  BOOLEAN: "BOOLEAN",
  EMAIL: "EMAIL",
  FLOAT: "FLOAT",
  INTEGER: "INTEGER",
  JSON: "JSON",
  STRING: "STRING",
  URL: "URL",
} as const;
