/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminOperationsSystemHealthListStatus =
  (typeof AdminOperationsSystemHealthListStatus)[keyof typeof AdminOperationsSystemHealthListStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminOperationsSystemHealthListStatus = {
  Degraded: "Degraded",
  Down: "Down",
  Operational: "Operational",
} as const;
