/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminConversationsListEscalationStatus =
  (typeof AdminConversationsListEscalationStatus)[keyof typeof AdminConversationsListEscalationStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminConversationsListEscalationStatus = {
  assigned: "assigned",
  closed: "closed",
  in_progress: "in_progress",
  none: "none",
  pending: "pending",
  resolved: "resolved",
} as const;
