/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedRecommendationList } from "./paginatedRecommendationList";
import type { AdminIntelligenceRecommendationsList200Meta } from "./adminIntelligenceRecommendationsList200Meta";

export type AdminIntelligenceRecommendationsList200 = {
  data: PaginatedRecommendationList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceRecommendationsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
