/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ChatMessage } from "./chatMessage";
import type { AdminIntelligenceMessagesUpdate200Meta } from "./adminIntelligenceMessagesUpdate200Meta";

export type AdminIntelligenceMessagesUpdate200 = {
  data: ChatMessage;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceMessagesUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
