/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EngineeringLabTool } from "./engineeringLabTool";
import type { AdminContentLabToolsRetrieve200Meta } from "./adminContentLabToolsRetrieve200Meta";

export type AdminContentLabToolsRetrieve200 = {
  data: EngineeringLabTool;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentLabToolsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
