/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LabWorkspace } from "./labWorkspace";
import type { AdminLabWorkspacesRetrieve200Meta } from "./adminLabWorkspacesRetrieve200Meta";

export type AdminLabWorkspacesRetrieve200 = {
  data: LabWorkspace;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminLabWorkspacesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
