/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Service } from "./service";
import type { AdminContentServicesPartialUpdate200Meta } from "./adminContentServicesPartialUpdate200Meta";

export type AdminContentServicesPartialUpdate200 = {
  data: Service;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminContentServicesPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
