/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminMessage } from "./adminMessage";
import type { AdminPerformanceRetrieve200Meta } from "./adminPerformanceRetrieve200Meta";

export type AdminPerformanceRetrieve200 = {
  data: AdminMessage;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminPerformanceRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
