/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationSession } from "./conversationSession";
import type { AdminIntelligenceConversationsPartialUpdate200Meta } from "./adminIntelligenceConversationsPartialUpdate200Meta";

export type AdminIntelligenceConversationsPartialUpdate200 = {
  data: ConversationSession;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminIntelligenceConversationsPartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
