/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedProposalList } from "./paginatedProposalList";
import type { AdminBusinessProposalsList200Meta } from "./adminBusinessProposalsList200Meta";

export type AdminBusinessProposalsList200 = {
  data: PaginatedProposalList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AdminBusinessProposalsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
