/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type AdminAnalyticsKnowledgeRetrieveParams = {
  /**
   * Start date (ISO 8601, e.g. 2025-01-01)
   */
  date_from?: string;
  /**
   * End date (ISO 8601, e.g. 2025-12-31)
   */
  date_to?: string;
  /**
   * Predefined period: today, week, month, quarter, year
   */
  period?: string;
};
