/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemHealthResponse } from "./systemHealthResponse";
import type { ApiHealthSystemRetrieve200Meta } from "./apiHealthSystemRetrieve200Meta";

export type ApiHealthSystemRetrieve200 = {
  data: SystemHealthResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: ApiHealthSystemRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
