/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LiveHealthResponse } from "./liveHealthResponse";
import type { ApiHealthLiveRetrieve200Meta } from "./apiHealthLiveRetrieve200Meta";

export type ApiHealthLiveRetrieve200 = {
  data: LiveHealthResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: ApiHealthLiveRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
