/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface APIRequestLog {
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** @maxLength 255 */
  endpoint: string;
  error_message?: string;
  has_error?: boolean;
  /** Unique identifier for this record. */
  readonly id: string;
  /** Unique identifier for this record. */
  integration: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   * @nullable
   */
  latency_ms?: number | null;
  /** @maxLength 10 */
  method?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   * @nullable
   */
  status_code?: number | null;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
