/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AccessLevelEnum } from "./accessLevelEnum";
import type { AssetTypeEnum } from "./assetTypeEnum";

export interface AssetRequest {
  access_level?: AccessLevelEnum;
  /** @maxLength 255 */
  alt_text?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  asset_name: string;
  asset_type?: AssetTypeEnum;
  caption?: string;
  /**
   * File hash for integrity
   * @maxLength 255
   */
  checksum?: string;
  /** @nullable */
  expires_at?: string | null;
  /**
   * @minLength 1
   * @maxLength 1000
   */
  file_url: string;
  /**
   * e.g., '50% 50%' for CSS object-position
   * @maxLength 50
   */
  focal_point?: string;
  /**
   * e.g., intelligence_engine, billing_engine
   * @maxLength 100
   */
  generated_by?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  height?: number | null;
  /** @maxLength 100 */
  mime_type?: string;
  /**
   * Size in bytes
   * @minimum 0
   * @maximum 9223372036854776000
   */
  size?: number;
  /**
   * @minLength 1
   * @maxLength 50
   */
  storage_provider?: string;
  tags?: string;
  /**
   * @maxLength 1000
   * @nullable
   */
  thumbnail_url?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  uploaded_by?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   */
  version?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   * @nullable
   */
  width?: number | null;
}
