/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `image` - Image
 * `video` - Video
 * `pdf_report` - PDF Report
 * `invoice` - Invoice
 * `contract` - Contract
 * `other` - Other
 */
export type AssetTypeEnum = (typeof AssetTypeEnum)[keyof typeof AssetTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetTypeEnum = {
  image: "image",
  video: "video",
  pdf_report: "pdf_report",
  invoice: "invoice",
  contract: "contract",
  other: "other",
} as const;
