/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for audit log responses.
 */
export interface AuditLog {
  /**
   * Action type identifier
   * @maxLength 50
   */
  action: string;
  /**
   * Admin who performed the action
   * @nullable
   */
  actor?: string | null;
  /** @nullable */
  readonly actor_username: string | null;
  readonly created_at: string;
  /** Human-readable description of the change */
  description: string;
  readonly id: number;
  /** Extensible data: IP, user agent, old/new values */
  metadata?: unknown;
  /**
   * User who was acted upon
   * @nullable
   */
  target_user?: string | null;
}
