/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ChangePasswordResponse } from "./changePasswordResponse";
import type { AuthChangePasswordCreate200Meta } from "./authChangePasswordCreate200Meta";

export type AuthChangePasswordCreate200 = {
  data: ChangePasswordResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AuthChangePasswordCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
