/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";
import type { AuthMePartialUpdate200Meta } from "./authMePartialUpdate200Meta";

export type AuthMePartialUpdate200 = {
  data: User;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AuthMePartialUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
