/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LogoutResponse } from "./logoutResponse";
import type { AuthLogoutCreate200Meta } from "./authLogoutCreate200Meta";

export type AuthLogoutCreate200 = {
  data: LogoutResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: AuthLogoutCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
