/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `PENDING` - Pending
 * `STARTED` - Started
 * `SUCCESS` - Success
 * `FAILURE` - Failure
 * `REVOKED` - Revoked
 */
export type BackgroundJobStatusEnum =
  (typeof BackgroundJobStatusEnum)[keyof typeof BackgroundJobStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BackgroundJobStatusEnum = {
  PENDING: "PENDING",
  STARTED: "STARTED",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  REVOKED: "REVOKED",
} as const;
