/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { BackgroundJobResult } from "./backgroundJobResult";
import type { BackgroundJobStatusEnum } from "./backgroundJobStatusEnum";

export interface BackgroundJob {
  /**
   * @maxLength 255
   * @nullable
   */
  celery_task_id?: string | null;
  readonly created_at: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  readonly created_by: string | null;
  /** @nullable */
  error_message?: string | null;
  readonly id: string;
  /** @maxLength 255 */
  name: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  progress?: number;
  /** @nullable */
  result?: BackgroundJobResult;
  status?: BackgroundJobStatusEnum;
  readonly updated_at: string;
}
