/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface CalendarSlot {
  /** Unique identifier for this record. */
  consultant: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  end_time: string;
  /** Unique identifier for this record. */
  readonly id: string;
  is_booked?: boolean;
  start_time: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
