/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Products Built` - Products Built
 * `Architectures Designed` - Architectures Designed
 * `Case Studies` - Case Studies
 * `Engineering Excellence` - Engineering Excellence
 * `Internal Products` - Internal Products
 * `Technology Leadership` - Technology Leadership
 * `Research & Innovation` - Research & Innovation
 */
export type CapabilityFocusEnum =
  (typeof CapabilityFocusEnum)[keyof typeof CapabilityFocusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CapabilityFocusEnum = {
  Products_Built: "Products Built",
  Architectures_Designed: "Architectures Designed",
  Case_Studies: "Case Studies",
  Engineering_Excellence: "Engineering Excellence",
  Internal_Products: "Internal Products",
  Technology_Leadership: "Technology Leadership",
  "Research_&_Innovation": "Research & Innovation",
} as const;
