/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface Category {
  /** @maxLength 20 */
  color?: string;
  /** @maxLength 50 */
  icon?: string;
  readonly id: number;
  is_active?: boolean;
  /** @maxLength 100 */
  name: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  sort_order?: number;
}
