/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `web_widget` - Web Widget
 * `api` - API
 * `whatsapp` - WhatsApp
 * `other` - Other
 */
export type ChannelEnum = (typeof ChannelEnum)[keyof typeof ChannelEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChannelEnum = {
  web_widget: "web_widget",
  api: "api",
  whatsapp: "whatsapp",
  other: "other",
} as const;
