/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ChatRequest } from "./chatRequest";
import type { ChatCreate200Meta } from "./chatCreate200Meta";

export type ChatCreate200 = {
  data: ChatRequest;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: ChatCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
