/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ChatRequestRequestMetadata } from "./chatRequestRequestMetadata";

export interface ChatRequestRequest {
  /**
   * @minLength 1
   * @maxLength 2000
   */
  message: string;
  /** @nullable */
  metadata?: ChatRequestRequestMetadata;
  /** @nullable */
  session_id?: string | null;
  /**
   * Required if session_id is provided.
   * @minLength 1
   * @nullable
   */
  session_token?: string | null;
}
