/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RoleEnum } from "./roleEnum";

export interface ChatMessage {
  content: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  role: RoleEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  sequence_number?: number;
  /** Unique identifier for this record. */
  readonly session: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
