/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Enterprise` - Enterprise
 * `Startup` - Startup
 * `Government` - Government
 * `SMB` - SMB
 * `Internal` - Internal
 */
export type ClientTypeEnum =
  (typeof ClientTypeEnum)[keyof typeof ClientTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientTypeEnum = {
  Enterprise: "Enterprise",
  Startup: "Startup",
  Government: "Government",
  SMB: "SMB",
  Internal: "Internal",
} as const;
