/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface Company {
  /** @maxLength 100 */
  business_stage?: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** @maxLength 255 */
  industry?: string;
  /** @maxLength 255 */
  name: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  /**
   * Optimistic locking version
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  version?: number;
  /** @maxLength 200 */
  website?: string;
}
