/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface CompanyProfileRequest {
  address?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  company_name: string;
  company_story?: string;
  core_values?: string;
  /** @maxLength 254 */
  email?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  favicon?: string | null;
  full_description?: string;
  /**
   * @maxLength 200
   * @nullable
   */
  github?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  instagram?: string | null;
  /** @maxLength 255 */
  legal_name?: string;
  /**
   * @maxLength 200
   * @nullable
   */
  linkedin?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  logo?: string | null;
  mission?: string;
  /** @maxLength 50 */
  phone?: string;
  /** @maxLength 50 */
  primary_color?: string;
  /** @maxLength 50 */
  secondary_color?: string;
  short_description?: string;
  status?: Status227Enum;
  /** @maxLength 255 */
  tagline?: string;
  /**
   * @maxLength 200
   * @nullable
   */
  twitter?: string | null;
  vision?: string;
  /** @maxLength 50 */
  whatsapp?: string;
}
