/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface CompanyRequest {
  /** @maxLength 100 */
  business_stage?: string;
  /** @maxLength 255 */
  industry?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * Optimistic locking version
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  version?: number;
  /** @maxLength 200 */
  website?: string;
}
