/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Pending` - Pending
 * `Booked` - Booked
 * `Completed` - Completed
 * `Cancelled` - Cancelled
 */
export type ConsultationSessionStatusEnum =
  (typeof ConsultationSessionStatusEnum)[keyof typeof ConsultationSessionStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConsultationSessionStatusEnum = {
  Pending: "Pending",
  Booked: "Booked",
  Completed: "Completed",
  Cancelled: "Cancelled",
} as const;
