/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ConsultationTypeRequest {
  description?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  duration_minutes?: number;
  is_active?: boolean;
  /**
   * e.g., Discovery Call, Technical Deep Dive, Architecture Review
   * @minLength 1
   * @maxLength 100
   */
  name: string;
}
