/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationSessionStatusEnum } from "./consultationSessionStatusEnum";

export interface ConsultationSession {
  /** Context generated by AI before the meeting */
  ai_handoff_context?: unknown;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  business_lead?: string | null;
  /** Unique identifier for this record. */
  consultation_type: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  intelligence_profile?: string | null;
  /** @maxLength 200 */
  meeting_link?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  partnership_model?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  slot?: string | null;
  status?: ConsultationSessionStatusEnum;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
