/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationStatusEnum } from "./consultationStatusEnum";

export interface ConsultationRequest {
  /** Unique identifier for this record. */
  lead: string;
  /** @maxLength 200 */
  meeting_link?: string;
  notes?: string;
  scheduled_at: string;
  status?: ConsultationStatusEnum;
}
