/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ConsultationSessionCreateRequest {
  ai_context?: unknown;
  architecture_summary?: unknown;
  /** Unique identifier for this record. */
  consultation_type: string;
  cost_estimation?: unknown;
  lab_context?: unknown;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  partnership_model?: string | null;
  recommended_services?: unknown;
  recommended_stack?: unknown;
  user_details: unknown;
}
