/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Scheduled` - Scheduled
 * `Completed` - Completed
 * `Cancelled` - Cancelled
 */
export type ConsultationStatusEnum =
  (typeof ConsultationStatusEnum)[keyof typeof ConsultationStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConsultationStatusEnum = {
  Scheduled: "Scheduled",
  Completed: "Completed",
  Cancelled: "Cancelled",
} as const;
