/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ContactRequest {
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /**
   * @minLength 1
   * @maxLength 254
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  first_name: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  last_name: string;
  /**
   * e.g., Founder, CTO
   * @maxLength 100
   */
  role?: string;
  /**
   * Optimistic locking version
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  version?: number;
}
