/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ContractStatusEnum } from "./contractStatusEnum";

export interface ContractRequest {
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  contract_asset?: string | null;
  /** Unique identifier for this record. */
  proposal: string;
  /** @nullable */
  signed_at?: string | null;
  status?: ContractStatusEnum;
}
