/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Pending` - Pending
 * `Signed` - Signed
 */
export type ContractStatusEnum =
  (typeof ContractStatusEnum)[keyof typeof ContractStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContractStatusEnum = {
  Pending: "Pending",
  Signed: "Signed",
} as const;
