/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface Contact {
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 100 */
  first_name: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** @maxLength 100 */
  last_name: string;
  /**
   * e.g., Founder, CTO
   * @maxLength 100
   */
  role?: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  /**
   * Optimistic locking version
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  version?: number;
}
