/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ConversationSession {
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  readonly last_message_at: string;
  metadata?: string;
  /** Unique identifier for this record. */
  profile: string;
  readonly session_id: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
