/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TrendSection } from "./trendSection";
import type { PlatformInsightsSection } from "./platformInsightsSection";
import type { ExecutiveMetricsSection } from "./executiveMetricsSection";

export interface CrmAnalyticsResponse {
  activity_trends: TrendSection;
  crm_funnel: TrendSection;
  crm_insights: PlatformInsightsSection;
  executive_metrics: ExecutiveMetricsSection;
  followup_analytics: TrendSection;
  status_distribution: TrendSection;
  user_performance: PlatformInsightsSection;
}
