/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `BEGINNER` - Beginner
 * `INTERMEDIATE` - Intermediate
 * `ADVANCED` - Advanced
 * `ENTERPRISE` - Enterprise
 */
export type DifficultyLevelEnum =
  (typeof DifficultyLevelEnum)[keyof typeof DifficultyLevelEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DifficultyLevelEnum = {
  BEGINNER: "BEGINNER",
  INTERMEDIATE: "INTERMEDIATE",
  ADVANCED: "ADVANCED",
  ENTERPRISE: "ENTERPRISE",
} as const;
