/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface EngineeringLabTool {
  /**
   * e.g., Architecture, Cost Estimation, Security
   * @maxLength 100
   */
  category: string;
  description?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  features?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status227Enum;
  /** @maxLength 255 */
  title: string;
}
