/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `none` - None
 * `pending` - Pending
 * `assigned` - Assigned
 * `in_progress` - In Progress
 * `resolved` - Resolved
 * `closed` - Closed
 */
export type EscalationStatusEnum =
  (typeof EscalationStatusEnum)[keyof typeof EscalationStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EscalationStatusEnum = {
  none: "none",
  pending: "pending",
  assigned: "assigned",
  in_progress: "in_progress",
  resolved: "resolved",
  closed: "closed",
} as const;
