/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface FAQRequest {
  /** @minLength 1 */
  answer: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  featured?: boolean;
  /**
   * @minLength 1
   * @maxLength 500
   */
  question: string;
  status?: Status227Enum;
}
