/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RatingEnum } from "./ratingEnum";

export interface FeedbackCreateRequest {
  /** @maxLength 1000 */
  comment?: string;
  /** @nullable */
  message_id?: number | null;
  rating: RatingEnum;
  session_id: string;
  /** @minLength 1 */
  session_token: string;
}
