/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `call` - Call
 * `meeting` - Meeting
 * `email` - Email
 * `demo` - Demo
 * `other` - Other
 */
export type FollowupTypeEnum =
  (typeof FollowupTypeEnum)[keyof typeof FollowupTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FollowupTypeEnum = {
  call: "call",
  meeting: "meeting",
  email: "email",
  demo: "demo",
  other: "other",
} as const;
