/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface GlobalSearchResult {
  /** Entity ID */
  id: number;
  /** Display subtitle or email */
  subtitle: string;
  /** Display title */
  title: string;
  /** Entity type (lead, company, project) */
  type: string;
  /** Admin OS route path */
  url: string;
}
