/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `GENERAL` - General
 * `AI` - AI
 * `CRM` - CRM
 * `KNOWLEDGE_BASE` - Knowledge Base
 * `ANALYTICS` - Analytics
 * `NOTIFICATIONS` - Notifications
 * `EMAIL` - Email
 * `SECURITY` - Security
 * `FEATURES` - Features
 * `APPEARANCE` - Appearance
 * `MAINTENANCE` - Maintenance
 */
export type GroupEnum = (typeof GroupEnum)[keyof typeof GroupEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GroupEnum = {
  GENERAL: "GENERAL",
  AI: "AI",
  CRM: "CRM",
  KNOWLEDGE_BASE: "KNOWLEDGE_BASE",
  ANALYTICS: "ANALYTICS",
  NOTIFICATIONS: "NOTIFICATIONS",
  EMAIL: "EMAIL",
  SECURITY: "SECURITY",
  FEATURES: "FEATURES",
  APPEARANCE: "APPEARANCE",
  MAINTENANCE: "MAINTENANCE",
} as const;
