/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `healthy` - healthy
 * `warning` - warning
 * `error` - error
 * `disabled` - disabled
 */
export type HealthStatusEnum =
  (typeof HealthStatusEnum)[keyof typeof HealthStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthStatusEnum = {
  healthy: "healthy",
  warning: "warning",
  error: "error",
  disabled: "disabled",
} as const;
