/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { HealthCheckResponse } from "./healthCheckResponse";
import type { HealthRetrieve2200Meta } from "./healthRetrieve2200Meta";

export type HealthRetrieve2200 = {
  data: HealthCheckResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: HealthRetrieve2200Meta;
  /** Always true for successful requests */
  success: boolean;
};
