/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Industry } from "./industry";
import type { Portfolio } from "./portfolio";
import type { Service } from "./service";
import type { Testimonial } from "./testimonial";
import type { Status227Enum } from "./status227Enum";

export interface Homepage {
  /**
   * @maxLength 200
   * @nullable
   */
  canonical?: string | null;
  /** The date and time when this record was created. */
  readonly created_at: string;
  readonly featured_industries: readonly Industry[];
  readonly featured_portfolios: readonly Portfolio[];
  readonly featured_services: readonly Service[];
  readonly featured_testimonials: readonly Testimonial[];
  /** @maxLength 255 */
  hero_cta_link?: string;
  /** @maxLength 100 */
  hero_cta_text?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  hero_image?: string | null;
  readonly hero_image_url: string;
  hero_subtitle?: string;
  /** @maxLength 255 */
  hero_title?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** @maxLength 500 */
  keywords?: string;
  meta_description?: string;
  /** @maxLength 255 */
  meta_title?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  og_image?: string | null;
  /** List of steps or points */
  process_content?: unknown;
  /** @maxLength 255 */
  process_title?: string;
  /** @maxLength 50 */
  robots?: string;
  status?: Status227Enum;
  /** @maxLength 255 */
  title?: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  why_b10_content?: string;
  /** @maxLength 255 */
  why_b10_title?: string;
}
