/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Investigating` - Investigating
 * `Identified` - Identified
 * `Monitoring` - Monitoring
 * `Resolved` - Resolved
 */
export type IncidentStatusEnum =
  (typeof IncidentStatusEnum)[keyof typeof IncidentStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IncidentStatusEnum = {
  Investigating: "Investigating",
  Identified: "Identified",
  Monitoring: "Monitoring",
  Resolved: "Resolved",
} as const;
