/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface IndustryUseCaseRequest {
  /** @maxLength 50 */
  badge?: string;
  /** @minLength 1 */
  description: string;
  /** @maxLength 100 */
  icon?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
}
