/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface IndustryUseCase {
  /** @maxLength 50 */
  badge?: string;
  description: string;
  /** @maxLength 100 */
  icon?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** @maxLength 255 */
  title: string;
}
