/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface IntegrationCredentialRequest {
  /** @maxLength 255 */
  api_key?: string;
  is_active?: boolean;
  /** Any additional config like region, endpoints */
  metadata?: unknown;
  /** @maxLength 255 */
  secret_key?: string;
  /**
   * e.g., OpenRouter, Cloudinary, SendGrid, Stripe
   * @minLength 1
   * @maxLength 100
   */
  service_name: string;
  /** @maxLength 255 */
  webhook_secret?: string;
}
