/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface IntelligenceSummaryResponse {
  /** @nullable */
  budget: string | null;
  completion_breakdown: string;
  /** @nullable */
  consultation: string | null;
  /** @nullable */
  industry: string | null;
  lab_reports: string[];
  lead_score: number;
  /** @nullable */
  persona: string | null;
  profile_completion: number;
  recommendations: string[];
  /** @nullable */
  timeline: string | null;
}
