/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for retrieving a specific version detail.
 */
export interface KnowledgeEntryVersionDetail {
  readonly category_snapshot: unknown;
  readonly change_summary: string;
  readonly content: string;
  readonly created_at: string;
  readonly created_by: string;
  readonly id: string;
  readonly knowledge_entry: string;
  readonly status: string;
  readonly structured_data: unknown;
  readonly tags_snapshot: unknown;
  readonly title: string;
  readonly version_number: number;
}
