/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for listing versions of a knowledge entry.
 */
export interface KnowledgeEntryVersionList {
  readonly change_summary: string;
  readonly created_at: string;
  readonly created_by: string;
  readonly id: string;
  readonly knowledge_entry: string;
  readonly status: string;
  readonly version_number: number;
}
