/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from "./category";
import type { SourceE97Enum } from "./sourceE97Enum";
import type { StatusDaeEnum } from "./statusDaeEnum";
import type { Tag } from "./tag";

/**
 * Read-only serializer for detail views (full fields).
 */
export interface KnowledgeEntryDetail {
  readonly category: Category;
  readonly content: string;
  readonly created_at: string;
  readonly created_by: string;
  readonly id: string;
  /** @nullable */
  readonly published_at: string | null;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
  readonly sort_order: number;
  readonly source: SourceE97Enum;
  readonly status: StatusDaeEnum;
  readonly structured_data: unknown;
  readonly tags: readonly Tag[];
  readonly title: string;
  readonly updated_at: string;
  readonly updated_by: string;
}
