/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TrendSection } from "./trendSection";
import type { ExecutiveMetricsSection } from "./executiveMetricsSection";
import type { PlatformInsightsSection } from "./platformInsightsSection";

export interface KnowledgeAnalyticsResponse {
  category_distribution: TrendSection;
  draft_growth: TrendSection;
  executive_metrics: ExecutiveMetricsSection;
  knowledge_growth: TrendSection;
  knowledge_insights: PlatformInsightsSection;
  published_growth: TrendSection;
  tag_distribution: TrendSection;
}
