/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SourceE97Enum } from "./sourceE97Enum";

/**
 * Write serializer for create/update operations.
 */
export interface KnowledgeEntryWriteRequest {
  category: number;
  change_summary?: string;
  content?: string;
  /** @minimum 0 */
  sort_order?: number;
  source?: SourceE97Enum;
  structured_data?: string;
  tags?: number[];
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
}
