/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LabReport {
  /** Raw data inputs/outputs from the tool */
  context_data?: unknown;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /**
   * The generated PDF or JSON asset
   * @nullable
   */
  report_asset?: string | null;
  /** Unique identifier for this record. */
  tool: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  /** Unique identifier for this record. */
  workspace: string;
}
