/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LabToolRequest {
  description?: string;
  is_enabled?: boolean;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * e.g., mvp_planner, cost_estimator, tech_stack_advisor
   * @minLength 1
   * @maxLength 100
   */
  tool_identifier: string;
}
