/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LabTool {
  /** The date and time when this record was created. */
  readonly created_at: string;
  description?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  is_enabled?: boolean;
  /** @maxLength 100 */
  name: string;
  /**
   * e.g., mvp_planner, cost_estimator, tech_stack_advisor
   * @maxLength 100
   */
  tool_identifier: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
