/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LabWorkspace {
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** Unique identifier for this record. */
  intelligence_profile: string;
  is_active?: boolean;
  /**
   * e.g., Startup MVP Workspace
   * @maxLength 255
   */
  name: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
