/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutiveMetricsSection } from "./executiveMetricsSection";
import type { TrendSection } from "./trendSection";
import type { PlatformInsightsSection } from "./platformInsightsSection";

export interface LeadAnalyticsResponse {
  executive_metrics: ExecutiveMetricsSection;
  growth_trend: TrendSection;
  lead_funnel: TrendSection;
  lead_insights: PlatformInsightsSection;
  lead_sources: TrendSection;
  score_distribution: TrendSection;
  status_distribution: TrendSection;
}
