/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LeadNote {
  readonly author: string;
  /** @nullable */
  readonly author_id: string | null;
  readonly created_at: string;
  readonly id: string;
  readonly lead: string;
  note: string;
}
