/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LeadAttachment {
  /** @maxLength 255 */
  file_name: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  file_size: number;
  /** @maxLength 1000 */
  file_url: string;
  readonly id: string;
  is_public?: boolean;
  /** @maxLength 100 */
  mime_type: string;
  readonly uploaded_at: string;
}
