/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PriorityD67Enum } from "./priorityD67Enum";
import type { Status639Enum } from "./status639Enum";

export interface LeadUpdateRequest {
  priority?: PriorityD67Enum;
  status?: Status639Enum;
}
