/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadStatusEnum } from "./leadStatusEnum";

export interface Lead {
  /**
   * e.g., Founder, CTO
   * @maxLength 100
   */
  ai_persona?: string;
  /** Recommended services, partners, etc. */
  ai_recommendations?: unknown;
  /**
   * Lead score generated by AI
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  ai_score?: number;
  /** Summary of AI conversations */
  ai_summary?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  assigned_to?: string | null;
  /** @maxLength 100 */
  budget_range?: string;
  /** @maxLength 255 */
  company?: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** @maxLength 254 */
  email: string;
  /** @maxLength 100 */
  first_name: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** Generated architecture/cost reports */
  lab_reports?: unknown;
  /** @maxLength 100 */
  last_name: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  linked_company?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  linked_contact?: string | null;
  /** @maxLength 100 */
  source?: string;
  status?: LeadStatusEnum;
  /** @maxLength 100 */
  timeline_expectation?: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  /**
   * Optimistic locking version
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  version?: number;
  /** List of pages visited */
  website_activity?: unknown;
}
