/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `chatbot` - Chatbot
 * `website_contact_form` - Website Contact Form
 * `manual` - Manual
 * `api` - API
 * `website_service_request` - Website Service Request
 * `website_book_meeting` - Website Book Meeting
 * `website_partnership` - Website Partnership
 * `website_careers` - Website Careers
 */
export type LeadDetailSourceEnum =
  (typeof LeadDetailSourceEnum)[keyof typeof LeadDetailSourceEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadDetailSourceEnum = {
  chatbot: "chatbot",
  website_contact_form: "website_contact_form",
  manual: "manual",
  api: "api",
  website_service_request: "website_service_request",
  website_book_meeting: "website_book_meeting",
  website_partnership: "website_partnership",
  website_careers: "website_careers",
} as const;
