/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityTypeEnum } from "./activityTypeEnum";

export interface LeadActivity {
  activity_type: ActivityTypeEnum;
  readonly created_at: string;
  readonly id: string;
  readonly lead: string;
  /** @nullable */
  notes?: string | null;
}
