/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - Pending
 * `completed` - Completed
 * `cancelled` - Cancelled
 */
export type LeadFollowUpStatusEnum =
  (typeof LeadFollowUpStatusEnum)[keyof typeof LeadFollowUpStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadFollowUpStatusEnum = {
  pending: "pending",
  completed: "completed",
  cancelled: "cancelled",
} as const;
