/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `New` - New
 * `Qualified` - Qualified
 * `Proposal` - Proposal Sent
 * `Negotiation` - Negotiation
 * `Won` - Won
 * `Lost` - Lost
 */
export type LeadStatusEnum =
  (typeof LeadStatusEnum)[keyof typeof LeadStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeadStatusEnum = {
  New: "New",
  Qualified: "Qualified",
  Proposal: "Proposal",
  Negotiation: "Negotiation",
  Won: "Won",
  Lost: "Lost",
} as const;
