/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LeadAttachment } from "./leadAttachment";
import type { ConversationSession } from "./conversationSession";
import type { PriorityD67Enum } from "./priorityD67Enum";
import type { LeadDetailSourceEnum } from "./leadDetailSourceEnum";
import type { Status639Enum } from "./status639Enum";

export interface LeadDetail {
  /**
   * Unique identifier for this record.
   * @nullable
   */
  assigned_admin?: string | null;
  readonly attachments: readonly LeadAttachment[];
  /**
   * @maxLength 100
   * @nullable
   */
  budget_range?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  company_name?: string | null;
  readonly conversation: ConversationSession;
  readonly created_at: string;
  /**
   * @maxLength 254
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  full_name?: string | null;
  readonly id: string;
  /**
   * @maxLength 255
   * @nullable
   */
  industry?: string | null;
  /** @nullable */
  last_contacted_at?: string | null;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  lead_score?: number;
  notification_sent?: boolean;
  /**
   * @maxLength 50
   * @nullable
   */
  phone?: string | null;
  priority?: PriorityD67Enum;
  /**
   * @maxLength 255
   * @nullable
   */
  project_type?: string | null;
  /** @nullable */
  qualified_at?: string | null;
  /** @nullable */
  requirements?: string | null;
  source?: LeadDetailSourceEnum;
  status?: Status639Enum;
  /**
   * @maxLength 100
   * @nullable
   */
  timeline?: string | null;
  readonly updated_at: string;
}
