/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `NAVBAR` - Navbar
 * `FOOTER` - Footer
 * `MEGA_MENU` - Mega Menu
 * `SIDEBAR` - Sidebar
 * `MOBILE` - Mobile
 * `LEGAL` - Legal
 */
export type LocationEnum = (typeof LocationEnum)[keyof typeof LocationEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocationEnum = {
  NAVBAR: "NAVBAR",
  FOOTER: "FOOTER",
  MEGA_MENU: "MEGA_MENU",
  SIDEBAR: "SIDEBAR",
  MOBILE: "MOBILE",
  LEGAL: "LEGAL",
} as const;
