/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MaintenanceLog {
  /** The date and time when this record was created. */
  readonly created_at: string;
  description: string;
  /** Unique identifier for this record. */
  readonly id: string;
  readonly performed_at: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  performed_by?: string | null;
  /** Unique identifier for this record. */
  project: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
