/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `text` - Text
 * `quick_reply` - Quick Reply
 * `card` - Card
 * `form` - Form
 * `system_event` - System Event
 */
export type MessageTypeEnum =
  (typeof MessageTypeEnum)[keyof typeof MessageTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageTypeEnum = {
  text: "text",
  quick_reply: "quick_reply",
  card: "card",
  form: "form",
  system_event: "system_event",
} as const;
