/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface Metric {
  /** @nullable */
  difference?: number | null;
  enabled?: boolean;
  /** @nullable */
  growth_percentage?: number | null;
  /** @nullable */
  previous_value?: number | null;
  title: string;
  /** @nullable */
  value?: number | null;
}
