/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status210Enum } from "./status210Enum";

export interface MigrationRequestRequest {
  /** Unique identifier for this record. */
  project: string;
  /** @nullable */
  scheduled_at?: string | null;
  status?: Status210Enum;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
}
