/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LocationEnum } from "./locationEnum";
import type { Status227Enum } from "./status227Enum";
import type { VisibilityEnum } from "./visibilityEnum";

export interface NavigationItemRequest {
  /** @maxLength 50 */
  badge?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /** @maxLength 100 */
  icon?: string;
  is_external?: boolean;
  location?: LocationEnum;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  parent?: string | null;
  /** List of required permission strings */
  permissions?: unknown;
  status?: Status227Enum;
  /**
   * _blank, _self, etc.
   * @maxLength 50
   */
  target?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  /**
   * @minLength 1
   * @maxLength 500
   */
  url: string;
  visibility?: VisibilityEnum;
}
