/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `SYSTEM` - System
 * `CRM` - CRM
 * `LEADS` - Leads
 * `KNOWLEDGE` - Knowledge
 * `USERS` - Users
 * `ROLES` - Roles
 * `SETTINGS` - Settings
 * `ANALYTICS` - Analytics
 * `AI` - AI
 * `AUTHENTICATION` - Authentication
 * `DEPLOYMENT` - Deployment
 * `SECURITY` - Security
 */
export type NotificationCategoryEnum =
  (typeof NotificationCategoryEnum)[keyof typeof NotificationCategoryEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationCategoryEnum = {
  SYSTEM: "SYSTEM",
  CRM: "CRM",
  LEADS: "LEADS",
  KNOWLEDGE: "KNOWLEDGE",
  USERS: "USERS",
  ROLES: "ROLES",
  SETTINGS: "SETTINGS",
  ANALYTICS: "ANALYTICS",
  AI: "AI",
  AUTHENTICATION: "AUTHENTICATION",
  DEPLOYMENT: "DEPLOYMENT",
  SECURITY: "SECURITY",
} as const;
