/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { NotificationCategoryEnum } from "./notificationCategoryEnum";
import type { TypeEnum } from "./typeEnum";

export interface Notification {
  readonly action_url: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  readonly actor: string | null;
  readonly actor_name: string;
  readonly category: NotificationCategoryEnum;
  readonly created_at: string;
  readonly id: string;
  readonly is_read: boolean;
  readonly message: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  readonly recipient: string | null;
  readonly recipient_name: string;
  readonly title: string;
  readonly type: TypeEnum;
}
