/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutiveMetricsSection } from "./executiveMetricsSection";
import type { GrowthMetricsSection } from "./growthMetricsSection";
import type { ModuleHealthSection } from "./moduleHealthSection";
import type { PlatformInsightsSection } from "./platformInsightsSection";
import type { RecentTrendsSection } from "./recentTrendsSection";

export interface OverviewResponse {
  executive_metrics: ExecutiveMetricsSection;
  growth_metrics: GrowthMetricsSection;
  module_health: ModuleHealthSection;
  platform_insights: PlatformInsightsSection;
  recent_trends: RecentTrendsSection;
}
