/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TimelineEvent } from "./timelineEvent";

export interface PaginatedTimelineEventList {
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: TimelineEvent[];
}
