/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PartnershipModel {
  description?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  is_active?: boolean;
  /**
   * e.g., Project Based, Retainer, Equity Partner
   * @maxLength 100
   */
  name: string;
}
