/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedConsultationReportRequest {
  /** Notes pushed to the CRM after meeting */
  crm_handoff_notes?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  report_asset?: string | null;
  /** Unique identifier for this record. */
  session?: string;
}
