/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProposalStatusEnum } from "./proposalStatusEnum";

export interface PatchedProposalRequest {
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  amount?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  description?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  lead?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  proposal_asset?: string | null;
  status?: ProposalStatusEnum;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
}
