/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface PatchedIndustryRequest {
  /** @maxLength 50 */
  badge?: string;
  /** Flexible page content: problems, solutions, metrics, tech stack, etc. */
  content?: unknown;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  content_version?: number;
  /** @minLength 1 */
  description?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /**
   * Icon name for lucide-react (e.g. 'Building2')
   * @maxLength 100
   */
  icon_name?: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status227Enum;
  /**
   * Short summary for industry cards
   * @maxLength 500
   */
  summary?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
}
