/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for role update (PATCH) requests.
 */
export interface PatchedRoleUpdateRequest {
  /**
   * @minLength 1
   * @maxLength 150
   */
  name?: string;
}
