/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AnalyticEventCategoryEnum } from "./analyticEventCategoryEnum";

export interface PatchedAnalyticEventRequest {
  category?: AnalyticEventCategoryEnum;
  /**
   * e.g., PageView, AIChatStarted, MVPPlannerUsed, ConsultationBooked, ProposalAccepted
   * @minLength 1
   * @maxLength 100
   */
  event_name?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  intelligence_profile?: string | null;
  /** Payload of the event */
  metadata?: unknown;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  revenue_amount?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  session_cookie_id?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  url?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  user?: string | null;
}
