/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedTagRequest {
  is_active?: boolean;
  /**
   * @minLength 1
   * @maxLength 50
   */
  name?: string;
}
