/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedActivityTimelineRequest {
  content_type?: number;
  description?: string;
  /**
   * e.g., Website Visit, Form Submitted, Meeting, Proposal Sent
   * @minLength 1
   * @maxLength 100
   */
  event_type?: string;
  /** @maxLength 50 */
  icon?: string;
  object_id?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
}
