/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedCategoryRequest {
  /**
   * @minLength 1
   * @maxLength 20
   */
  color?: string;
  /** @maxLength 50 */
  icon?: string;
  is_active?: boolean;
  /**
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  sort_order?: number;
}
