/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchedSettingUpdateRequestSettings } from "./patchedSettingUpdateRequestSettings";

/**
 * Serializer for updating settings within a category (key-value pairs).
 */
export interface PatchedSettingUpdateRequest {
  settings?: PatchedSettingUpdateRequestSettings;
}
