/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedCalendarSlotRequest {
  /** Unique identifier for this record. */
  consultant?: string;
  end_time?: string;
  is_booked?: boolean;
  start_time?: string;
}
