/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedSEOMetadataRequest {
  /**
   * @maxLength 200
   * @nullable
   */
  canonical?: string | null;
  /** @maxLength 500 */
  keywords?: string;
  meta_description?: string;
  /** @maxLength 255 */
  meta_title?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  og_image?: string | null;
  /**
   * @minLength 1
   * @maxLength 50
   */
  robots?: string;
  /**
   * e.g., /solutions/saas-engineering
   * @minLength 1
   * @maxLength 255
   */
  route?: string;
}
