/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SeverityEnum } from "./severityEnum";
import type { IncidentStatusEnum } from "./incidentStatusEnum";

export interface PatchedIncidentRequest {
  /** @minLength 1 */
  description?: string;
  /** @nullable */
  resolved_at?: string | null;
  severity?: SeverityEnum;
  status?: IncidentStatusEnum;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
}
