/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedVisitorIntelligenceProfileRequest {
  browsing_context?: string;
  business_context?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  business_lead?: string | null;
  commercial_context?: string;
  consultation_context?: string;
  conversation_context?: string;
  /**
   * Founder, CTO, Enterprise, etc.
   * @maxLength 100
   */
  detected_persona?: string;
  lab_context?: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  lead_score?: number;
  lead_score_context?: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  qualification_status?: string;
  recommendation_context?: string;
  /**
   * @maxLength 255
   * @nullable
   */
  session_cookie_id?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  user?: string | null;
}
