/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { CapabilityFocusEnum } from "./capabilityFocusEnum";
import type { PatchedPortfolioRequestClientType } from "./patchedPortfolioRequestClientType";
import type { ProjectStatusEnum } from "./projectStatusEnum";
import type { Status227Enum } from "./status227Enum";

export interface PatchedPortfolioRequest {
  /** Architecture layers: [{layer, desc}] */
  architecture_stack?: unknown;
  /** @maxLength 50 */
  badge?: string;
  business_problem?: string;
  /** e.g., Products, Architectures, Research

* `Products Built` - Products Built
* `Architectures Designed` - Architectures Designed
* `Case Studies` - Case Studies
* `Engineering Excellence` - Engineering Excellence
* `Internal Products` - Internal Products
* `Technology Leadership` - Technology Leadership
* `Research & Innovation` - Research & Innovation */
  capability_focus?: CapabilityFocusEnum;
  /**
   * e.g., National Healthcare Provider (kept anonymous)
   * @maxLength 255
   */
  client_name?: string;
  client_type?: PatchedPortfolioRequestClientType;
  /** Rich page content: requirements, challenges, outcomes, cross-links, CTA */
  content?: unknown;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /**
   * e.g., 6 months, 18 months, Ongoing
   * @maxLength 100
   */
  engagement_duration?: string;
  /**
   * e.g., Technical Co-Founder, Project
   * @maxLength 255
   */
  engagement_type?: string;
  /**
   * 0 = not featured. 1-N = homepage display order
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  featured_order?: number;
  /**
   * e.g., Series B, Fortune 500, Early-Stage
   * @maxLength 100
   */
  industry_size?: string;
  /** Business impact metrics: [{metric, value}] */
  metrics?: unknown;
  project_status?: ProjectStatusEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  schema_version?: number;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status227Enum;
  /**
   * Short summary for hub cards
   * @maxLength 500
   */
  summary?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
}
