/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedMaintenanceLogRequest {
  /** @minLength 1 */
  description?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  performed_by?: string | null;
  /** Unique identifier for this record. */
  project?: string;
}
