/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface PatchedHomepageRequest {
  /**
   * @maxLength 200
   * @nullable
   */
  canonical?: string | null;
  /** @maxLength 255 */
  hero_cta_link?: string;
  /** @maxLength 100 */
  hero_cta_text?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  hero_image?: string | null;
  hero_subtitle?: string;
  /** @maxLength 255 */
  hero_title?: string;
  /** @maxLength 500 */
  keywords?: string;
  meta_description?: string;
  /** @maxLength 255 */
  meta_title?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  og_image?: string | null;
  /** List of steps or points */
  process_content?: unknown;
  /** @maxLength 255 */
  process_title?: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  robots?: string;
  status?: Status227Enum;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title?: string;
  why_b10_content?: string;
  /** @maxLength 255 */
  why_b10_title?: string;
}
