/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentStatusEnum } from "./paymentStatusEnum";

export interface PaymentRequest {
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  amount: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  invoice_asset?: string | null;
  /** @nullable */
  paid_at?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  project?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  proposal?: string | null;
  status?: PaymentStatusEnum;
}
