/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentStatusEnum } from "./paymentStatusEnum";

export interface Payment {
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  amount: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  invoice_asset?: string | null;
  /** @nullable */
  paid_at?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  project?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  proposal?: string | null;
  status?: PaymentStatusEnum;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
