/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Pending` - Pending
 * `Paid` - Paid
 * `Failed` - Failed
 */
export type PaymentStatusEnum =
  (typeof PaymentStatusEnum)[keyof typeof PaymentStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentStatusEnum = {
  Pending: "Pending",
  Paid: "Paid",
  Failed: "Failed",
} as const;
