/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PlatformFeatureRequest {
  description?: string;
  /** @maxLength 255 */
  display_name?: string;
  is_enabled?: boolean;
  /**
   * e.g. AI, Search, Knowledge, Reports
   * @minLength 1
   * @maxLength 100
   */
  key: string;
}
