/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { GroupEnum } from "./groupEnum";
import type { ValueTypeEnum } from "./valueTypeEnum";

export interface PlatformSetting {
  readonly created_at: string;
  description?: string;
  /** @maxLength 255 */
  display_name?: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  display_order?: number;
  group: GroupEnum;
  readonly id: string;
  is_editable?: boolean;
  is_public?: boolean;
  is_sensitive?: boolean;
  /** @maxLength 100 */
  key: string;
  readonly updated_at: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  readonly updated_by: string | null;
  validation_rules?: string;
  value?: string;
  value_type: ValueTypeEnum;
}
