/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AnalyticEvent } from "./analyticEvent";
import type { PlatformAnalyticsEventsUpdate200Meta } from "./platformAnalyticsEventsUpdate200Meta";

export type PlatformAnalyticsEventsUpdate200 = {
  data: AnalyticEvent;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PlatformAnalyticsEventsUpdate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
