/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformAnalyticsDashboardExecutiveRetrieve200Data } from "./platformAnalyticsDashboardExecutiveRetrieve200Data";
import type { PlatformAnalyticsDashboardExecutiveRetrieve200Meta } from "./platformAnalyticsDashboardExecutiveRetrieve200Meta";

export type PlatformAnalyticsDashboardExecutiveRetrieve200 = {
  data: PlatformAnalyticsDashboardExecutiveRetrieve200Data;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PlatformAnalyticsDashboardExecutiveRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
