/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AnalyticEvent } from "./analyticEvent";
import type { PlatformAnalyticsEventsRetrieve200Meta } from "./platformAnalyticsEventsRetrieve200Meta";

export type PlatformAnalyticsEventsRetrieve200 = {
  data: AnalyticEvent;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PlatformAnalyticsEventsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
