/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export type PlatformAnalyticsEventsListCategory =
  (typeof PlatformAnalyticsEventsListCategory)[keyof typeof PlatformAnalyticsEventsListCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformAnalyticsEventsListCategory = {
  AI: "AI",
  Business: "Business",
  Consultation: "Consultation",
  Lab: "Lab",
  Operations: "Operations",
  Website: "Website",
} as const;
