/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PlatformFeature {
  readonly created_at: string;
  description?: string;
  /** @maxLength 255 */
  display_name?: string;
  readonly id: string;
  is_enabled?: boolean;
  /**
   * e.g. AI, Search, Knowledge, Reports
   * @maxLength 100
   */
  key: string;
  readonly updated_at: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  readonly updated_by: string | null;
}
