/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request metadata and telemetry
 */
export type PlatformAnalyticsEventsPartialUpdate200Meta = {
  execution_time_ms?: number;
  pagination?: boolean;
  request_id?: string;
  timestamp?: string;
};
