/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `low` - Low
 * `medium` - Medium
 * `high` - High
 * `urgent` - Urgent
 */
export type PriorityD67Enum =
  (typeof PriorityD67Enum)[keyof typeof PriorityD67Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PriorityD67Enum = {
  low: "low",
  medium: "medium",
  high: "high",
  urgent: "urgent",
} as const;
