/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileUpdateRequestRequestValue } from "./profileUpdateRequestRequestValue";

export interface ProfileUpdateRequestRequest {
  /**
   * @minLength 1
   * @nullable
   */
  entity_slug?: string | null;
  /**
   * @minLength 1
   * @nullable
   */
  event?: string | null;
  /**
   * @minLength 1
   * @nullable
   */
  page_type?: string | null;
  /** @minLength 1 */
  session_cookie_id: string;
  /** @nullable */
  value?: ProfileUpdateRequestRequestValue;
}
