/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectStatusEnum } from "./projectStatusEnum";

export interface Project {
  client_portal_enabled?: boolean;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /** The date and time when this record was created. */
  readonly created_at: string;
  deliverables?: string;
  /** @nullable */
  end_date?: string | null;
  /** Unique identifier for this record. */
  readonly id: string;
  milestones?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  proposal?: string | null;
  /** @nullable */
  start_date?: string | null;
  status?: ProjectStatusEnum;
  /** @maxLength 255 */
  title: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  /**
   * Optimistic locking version
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  version?: number;
}
