/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Healthy` - Healthy
 * `At Risk` - At Risk
 * `Critical` - Critical
 */
export type ProjectHealthStatusEnum =
  (typeof ProjectHealthStatusEnum)[keyof typeof ProjectHealthStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectHealthStatusEnum = {
  Healthy: "Healthy",
  At_Risk: "At Risk",
  Critical: "Critical",
} as const;
