/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectHealthStatusEnum } from "./projectHealthStatusEnum";

export interface ProjectHealthRequest {
  /**
   * Unique identifier for this record.
   * @nullable
   */
  maintenance_plan?: string | null;
  notes?: string;
  /** Unique identifier for this record. */
  project: string;
  status?: ProjectHealthStatusEnum;
}
