/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Draft` - Draft
 * `Sent` - Sent
 * `Accepted` - Accepted
 * `Rejected` - Rejected
 */
export type ProposalStatusEnum =
  (typeof ProposalStatusEnum)[keyof typeof ProposalStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProposalStatusEnum = {
  Draft: "Draft",
  Sent: "Sent",
  Accepted: "Accepted",
  Rejected: "Rejected",
} as const;
