/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProposalStatusEnum } from "./proposalStatusEnum";

export interface Proposal {
  /** @pattern ^-?\d{0,10}(?:\.\d{0,2})?$ */
  amount?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  company?: string | null;
  /** The date and time when this record was created. */
  readonly created_at: string;
  description?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  lead?: string | null;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  proposal_asset?: string | null;
  status?: ProposalStatusEnum;
  /** @maxLength 255 */
  title: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
