/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedConsultationTypeList } from "./paginatedConsultationTypeList";
import type { PublicEngagementConsultationTypesList200Meta } from "./publicEngagementConsultationTypesList200Meta";

export type PublicEngagementConsultationTypesList200 = {
  data: PaginatedConsultationTypeList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicEngagementConsultationTypesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
