/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceCategory } from "./serviceCategory";
import type { PublicContentServiceCategoriesRetrieve200Meta } from "./publicContentServiceCategoriesRetrieve200Meta";

export type PublicContentServiceCategoriesRetrieve200 = {
  data: ServiceCategory;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentServiceCategoriesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
