/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Faq } from "./faq";
import type { PublicContentFaqsRetrieve200Meta } from "./publicContentFaqsRetrieve200Meta";

export type PublicContentFaqsRetrieve200 = {
  data: Faq;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentFaqsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
