/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { DecisionResponse } from "./decisionResponse";
import type { PublicIntelligenceDecisionRetrieve200Meta } from "./publicIntelligenceDecisionRetrieve200Meta";

export type PublicIntelligenceDecisionRetrieve200 = {
  data: DecisionResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceDecisionRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
