/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedNavigationItemList } from "./paginatedNavigationItemList";
import type { PublicContentNavigationList200Meta } from "./publicContentNavigationList200Meta";

export type PublicContentNavigationList200 = {
  data: PaginatedNavigationItemList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentNavigationList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
