/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedResourceCategoryList } from "./paginatedResourceCategoryList";
import type { PublicContentResourceCategoriesList200Meta } from "./publicContentResourceCategoriesList200Meta";

export type PublicContentResourceCategoriesList200 = {
  data: PaginatedResourceCategoryList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentResourceCategoriesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
