/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedTeamMemberList } from "./paginatedTeamMemberList";
import type { PublicContentTeamList200Meta } from "./publicContentTeamList200Meta";

export type PublicContentTeamList200 = {
  data: PaginatedTeamMemberList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentTeamList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
