/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PlatformSetting } from "./platformSetting";
import type { PublicSettingsRetrieve200Meta } from "./publicSettingsRetrieve200Meta";

export type PublicSettingsRetrieve200 = {
  data: PlatformSetting;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicSettingsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
