/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedResourceList } from "./paginatedResourceList";
import type { PublicContentResourcesList200Meta } from "./publicContentResourcesList200Meta";

export type PublicContentResourcesList200 = {
  data: PaginatedResourceList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentResourcesList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
