/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationSessionCreate } from "./consultationSessionCreate";
import type { PublicEngagementConsultationSessionCreate201Meta } from "./publicEngagementConsultationSessionCreate201Meta";

export type PublicEngagementConsultationSessionCreate201 = {
  data: ConsultationSessionCreate;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicEngagementConsultationSessionCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
