/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Resource } from "./resource";
import type { PublicContentResourcesRetrieve200Meta } from "./publicContentResourcesRetrieve200Meta";

export type PublicContentResourcesRetrieve200 = {
  data: Resource;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentResourcesRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
