/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PublicContactResponse } from "./publicContactResponse";
import type { PublicContactCreate201Meta } from "./publicContactCreate201Meta";

export type PublicContactCreate201 = {
  data: PublicContactResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContactCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
