/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { StartSessionResponse } from "./startSessionResponse";
import type { PublicIntelligenceSessionStartCreate201Meta } from "./publicIntelligenceSessionStartCreate201Meta";

export type PublicIntelligenceSessionStartCreate201 = {
  data: StartSessionResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceSessionStartCreate201Meta;
  /** Always true for successful requests */
  success: boolean;
};
