/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedCompanyProfileList } from "./paginatedCompanyProfileList";
import type { PublicContentCompanyProfileList200Meta } from "./publicContentCompanyProfileList200Meta";

export type PublicContentCompanyProfileList200 = {
  data: PaginatedCompanyProfileList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentCompanyProfileList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
