/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface PublicContactRequest {
  attachment?: Blob;
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  full_name: string;
  /**
   * @minLength 10
   * @maxLength 5000
   */
  message: string;
  /**
   * @minLength 10
   * @maxLength 20
   */
  phone_number: string;
}
