/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { GetSessionResponse } from "./getSessionResponse";
import type { PublicIntelligenceSessionRetrieve200Meta } from "./publicIntelligenceSessionRetrieve200Meta";

export type PublicIntelligenceSessionRetrieve200 = {
  data: GetSessionResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceSessionRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
