/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PublicContentResourcesListResourceType } from "./publicContentResourcesListResourceType";

export type PublicContentResourcesListParams = {
  category__slug?: string;
  /**
   * Which field to use when ordering the results.
   */
  ordering?: string;
  /**
   * A page number within the paginated result set.
   */
  page?: number;
  /**
   * * `engineering-intelligence` - Engineering Intelligence
   * `blog` - Blog
   * `guide` - Guide
   * `technology-guide` - Technology Guide
   */
  resource_type?: PublicContentResourcesListResourceType;
  /**
   * A search term.
   */
  search?: string;
};
