/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { VisitorIntelligenceProfile } from "./visitorIntelligenceProfile";
import type { PublicIntelligenceProfileRetrieve200Meta } from "./publicIntelligenceProfileRetrieve200Meta";

export type PublicIntelligenceProfileRetrieve200 = {
  data: VisitorIntelligenceProfile;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceProfileRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
