/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PaginatedFAQList } from "./paginatedFAQList";
import type { PublicContentFaqsList200Meta } from "./publicContentFaqsList200Meta";

export type PublicContentFaqsList200 = {
  data: PaginatedFAQList;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentFaqsList200Meta;
  /** Always true for successful requests */
  success: boolean;
};
