/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { RecommendationsResponse } from "./recommendationsResponse";
import type { PublicIntelligenceRecommendationsRetrieve200Meta } from "./publicIntelligenceRecommendationsRetrieve200Meta";

export type PublicIntelligenceRecommendationsRetrieve200 = {
  data: RecommendationsResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceRecommendationsRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
