/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { PublicIntelligenceMessageCreate200Meta } from "./publicIntelligenceMessageCreate200Meta";

export type PublicIntelligenceMessageCreate200 = {
  /** SSE Stream */
  data: Blob;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceMessageCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
