/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { CompanyProfile } from "./companyProfile";
import type { PublicContentCompanyProfileRetrieve200Meta } from "./publicContentCompanyProfileRetrieve200Meta";

export type PublicContentCompanyProfileRetrieve200 = {
  data: CompanyProfile;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicContentCompanyProfileRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
