/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ContextResponse } from "./contextResponse";
import type { PublicIntelligenceContextRetrieve200Meta } from "./publicIntelligenceContextRetrieve200Meta";

export type PublicIntelligenceContextRetrieve200 = {
  data: ContextResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceContextRetrieve200Meta;
  /** Always true for successful requests */
  success: boolean;
};
