/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileUpdateResponse } from "./profileUpdateResponse";
import type { PublicIntelligenceProfileUpdateCreate200Meta } from "./publicIntelligenceProfileUpdateCreate200Meta";

export type PublicIntelligenceProfileUpdateCreate200 = {
  data: ProfileUpdateResponse;
  /** Human-readable success message */
  message?: string;
  /** Request metadata and telemetry */
  meta: PublicIntelligenceProfileUpdateCreate200Meta;
  /** Always true for successful requests */
  success: boolean;
};
