/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `not_started` - Not Started
 * `gathering` - Gathering
 * `qualified` - Qualified
 * `disqualified` - Disqualified
 * `escalated_to_human` - Escalated To Human
 */
export type QualificationStateEnum =
  (typeof QualificationStateEnum)[keyof typeof QualificationStateEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const QualificationStateEnum = {
  not_started: "not_started",
  gathering: "gathering",
  qualified: "qualified",
  disqualified: "disqualified",
  escalated_to_human: "escalated_to_human",
} as const;
