/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface RecommendationRequest {
  /** @minLength 1 */
  content: string;
  is_accepted?: boolean;
  /** Unique identifier for this record. */
  profile: string;
  /**
   * e.g., Tech Stack, Consultation Type, Partnership Model
   * @minLength 1
   * @maxLength 100
   */
  recommendation_type: string;
}
