/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface Recommendation {
  content: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  is_accepted?: boolean;
  /** Unique identifier for this record. */
  profile: string;
  /**
   * e.g., Tech Stack, Consultation Type, Partnership Model
   * @maxLength 100
   */
  recommendation_type: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
