/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `engineering-intelligence` - Engineering Intelligence
 * `blog` - Blog
 * `guide` - Guide
 * `technology-guide` - Technology Guide
 */
export type ResourceTypeEnum =
  (typeof ResourceTypeEnum)[keyof typeof ResourceTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceTypeEnum = {
  "engineering-intelligence": "engineering-intelligence",
  blog: "blog",
  guide: "guide",
  "technology-guide": "technology-guide",
} as const;
