/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { DifficultyLevelEnum } from "./difficultyLevelEnum";
import type { ResourceTypeEnum } from "./resourceTypeEnum";
import type { Status227Enum } from "./status227Enum";

export interface ResourceRequest {
  /** @maxLength 50 */
  badge?: string;
  /** Rich content, takeaways, SEO fields, related_content cross-links */
  content?: unknown;
  /**
   * e.g., Blueprint, Playbook (sub-type)
   * @maxLength 100
   * @nullable
   */
  content_type?: string | null;
  difficulty_level?: DifficultyLevelEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /**
   * 0 = not featured. 1-N = homepage display order
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  featured_order?: number;
  /**
   * Calculated or manual score (e.g. 98)
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  intelligence_score?: number;
  /** @maxLength 50 */
  read_time?: string;
  resource_type?: ResourceTypeEnum;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  schema_version?: number;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status227Enum;
  summary?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
}
