/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `user` - User
 * `assistant` - Assistant
 * `system` - System
 */
export type RoleEnum = (typeof RoleEnum)[keyof typeof RoleEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleEnum = {
  user: "user",
  assistant: "assistant",
  system: "system",
} as const;
