/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for role detail responses.
 */
export interface RoleDetail {
  readonly id: number;
  /** @maxLength 150 */
  name: string;
  readonly permissions: string;
  readonly users_count: number;
}
