/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface SEOMetadata {
  /**
   * @maxLength 200
   * @nullable
   */
  canonical?: string | null;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  /** @maxLength 500 */
  keywords?: string;
  meta_description?: string;
  /** @maxLength 255 */
  meta_title?: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  og_image?: string | null;
  /** @maxLength 50 */
  robots?: string;
  /**
   * e.g., /solutions/saas-engineering
   * @maxLength 255
   */
  route: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
