/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface Service {
  /** @maxLength 50 */
  badge?: string;
  /** Detailed flexible page content */
  content?: unknown;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  content_version?: number;
  /** Detailed description */
  description: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /**
   * Icon name for lucide-react (e.g. 'Bot')
   * @maxLength 100
   */
  icon_name?: string;
  readonly icon_url: string;
  /** Unique identifier for this record. */
  readonly id: string;
  readonly related_industries_slugs: string;
  readonly related_services_slugs: string;
  /**
   * @maxLength 255
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  slug?: string;
  status?: Status227Enum;
  /**
   * Short summary for cards
   * @maxLength 500
   */
  summary?: string;
  /**
   * e.g., Core, Premium
   * @maxLength 100
   */
  tier?: string;
  /** @maxLength 255 */
  title: string;
}
