/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Category762Enum } from "./category762Enum";
import type { SettingPublicValue } from "./settingPublicValue";

/**
 * Serializer for public settings (no auth required).
 */
export interface SettingPublic {
  category: Category762Enum;
  /** @maxLength 100 */
  key: string;
  /** @nullable */
  value?: SettingPublicValue;
}
