/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Category762Enum } from "./category762Enum";
import type { SettingValue } from "./settingValue";

/**
 * Serializer for admin setting list/detail responses.
 */
export interface Setting {
  category: Category762Enum;
  /** @nullable */
  description?: string | null;
  readonly id: number;
  is_public?: boolean;
  /** @maxLength 100 */
  key: string;
  readonly updated_at: string;
  readonly updated_by_username: string;
  /** @nullable */
  value?: SettingValue;
}
