/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Minor` - Minor
 * `Major` - Major
 * `Critical` - Critical
 */
export type SeverityEnum = (typeof SeverityEnum)[keyof typeof SeverityEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SeverityEnum = {
  Minor: "Minor",
  Major: "Major",
  Critical: "Critical",
} as const;
