/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `manual` - Manual
 * `json_import` - JSON Import
 * `api` - API
 */
export type SourceE97Enum = (typeof SourceE97Enum)[keyof typeof SourceE97Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceE97Enum = {
  manual: "manual",
  json_import: "json_import",
  api: "api",
} as const;
