/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Pending` - Pending
 * `In Progress` - In Progress
 * `Completed` - Completed
 * `Failed` - Failed
 */
export type Status210Enum = (typeof Status210Enum)[keyof typeof Status210Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status210Enum = {
  Pending: "Pending",
  In_Progress: "In Progress",
  Completed: "Completed",
  Failed: "Failed",
} as const;
