/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `new` - New
 * `qualified` - Qualified
 * `proposal` - Proposal Sent
 * `negotiation` - Negotiation
 * `won` - Won
 * `lost` - Lost
 */
export type Status639Enum = (typeof Status639Enum)[keyof typeof Status639Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status639Enum = {
  new: "new",
  qualified: "qualified",
  proposal: "proposal",
  negotiation: "negotiation",
  won: "won",
  lost: "lost",
} as const;
