/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Active` - Active
 * `Inactive` - Inactive
 */
export type Status2d9Enum = (typeof Status2d9Enum)[keyof typeof Status2d9Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status2d9Enum = {
  Active: "Active",
  Inactive: "Inactive",
} as const;
