/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Draft` - Draft
 * `In Review` - In Review
 * `Approved` - Approved
 * `Scheduled` - Scheduled
 * `Published` - Published
 * `Archived` - Archived
 */
export type Status227Enum = (typeof Status227Enum)[keyof typeof Status227Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status227Enum = {
  Draft: "Draft",
  In_Review: "In Review",
  Approved: "Approved",
  Scheduled: "Scheduled",
  Published: "Published",
  Archived: "Archived",
} as const;
