/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `active` - Active
 * `idle` - Idle
 * `closed` - Closed
 * `escalated` - Escalated
 * `abandoned` - Abandoned
 */
export type Status088Enum = (typeof Status088Enum)[keyof typeof Status088Enum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status088Enum = {
  active: "active",
  idle: "idle",
  closed: "closed",
  escalated: "escalated",
  abandoned: "abandoned",
} as const;
