/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `draft` - Draft
 * `published` - Published
 * `archived` - Archived
 */
export type StatusDaeEnum = (typeof StatusDaeEnum)[keyof typeof StatusDaeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusDaeEnum = {
  draft: "draft",
  published: "published",
  archived: "archived",
} as const;
