/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Open` - Open
 * `In Progress` - In Progress
 * `Resolved` - Resolved
 * `Closed` - Closed
 */
export type SupportTicketStatusEnum =
  (typeof SupportTicketStatusEnum)[keyof typeof SupportTicketStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportTicketStatusEnum = {
  Open: "Open",
  In_Progress: "In Progress",
  Resolved: "Resolved",
  Closed: "Closed",
} as const;
