/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Low` - Low
 * `Medium` - Medium
 * `High` - High
 * `Urgent` - Urgent
 */
export type SupportTicketPriorityEnum =
  (typeof SupportTicketPriorityEnum)[keyof typeof SupportTicketPriorityEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SupportTicketPriorityEnum = {
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Urgent: "Urgent",
} as const;
