/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SupportTicketPriorityEnum } from "./supportTicketPriorityEnum";
import type { SupportTicketStatusEnum } from "./supportTicketStatusEnum";

export interface SupportTicket {
  /** The date and time when this record was created. */
  readonly created_at: string;
  description: string;
  /** Unique identifier for this record. */
  readonly id: string;
  is_sla_breached?: boolean;
  priority?: SupportTicketPriorityEnum;
  /** Unique identifier for this record. */
  project: string;
  /** Unique identifier for this record. */
  reported_by: string;
  status?: SupportTicketStatusEnum;
  /** @maxLength 255 */
  title: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
