/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface SystemHealthResponse {
  django_version: string;
  environment: string;
  git_commit: string;
  python_version: string;
  status: string;
  telemetry: string;
  timestamp: string;
  uptime_seconds: number;
  version: string;
}
