/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface SystemAuditLog {
  /**
   * e.g. CREATE, UPDATE, DELETE, RESTORE
   * @maxLength 50
   */
  action: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  readonly actor: string | null;
  /** Diff of changes */
  changes?: unknown;
  content_type: number;
  readonly content_type_model: string;
  readonly created_at: string;
  readonly id: string;
  /** @nullable */
  readonly ip_address: string | null;
  /** @nullable */
  object_id?: string | null;
}
