/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { SystemHealthStatusEnum } from "./systemHealthStatusEnum";

export interface SystemHealth {
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** Unique identifier for this record. */
  readonly id: string;
  readonly last_ping: string;
  /**
   * e.g., Redis, Celery, Database
   * @maxLength 100
   */
  service_name: string;
  status?: SystemHealthStatusEnum;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
