/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface Tag {
  readonly id: number;
  is_active?: boolean;
  /** @maxLength 50 */
  name: string;
  /** @pattern ^[-a-zA-Z0-9_]+$ */
  readonly slug: string;
}
