/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";

export interface TeamMember {
  bio?: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /** @maxLength 100 */
  department?: string;
  /** @maxLength 255 */
  designation: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /**
   * @maxLength 254
   * @nullable
   */
  email?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  github?: string | null;
  /** Unique identifier for this record. */
  readonly id: string;
  is_featured?: boolean;
  /**
   * @maxLength 200
   * @nullable
   */
  linkedin?: string | null;
  /** @maxLength 255 */
  name: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  photo?: string | null;
  readonly photo_url: string;
  skills?: string;
  status?: Status227Enum;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
