/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status2d9Enum } from "./status2d9Enum";

export interface TechnologyPartnershipRequest {
  /** Unique identifier for this record. */
  company: string;
  features?: string;
  status?: Status2d9Enum;
  /**
   * @minLength 1
   * @maxLength 100
   */
  tier: string;
}
