/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status2d9Enum } from "./status2d9Enum";

export interface TechnologyPartnership {
  /** Unique identifier for this record. */
  company: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  features?: string;
  /** Unique identifier for this record. */
  readonly id: string;
  status?: Status2d9Enum;
  /** @maxLength 100 */
  tier: string;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
}
