/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Status227Enum } from "./status227Enum";
import type { TestimonialTypeEnum } from "./testimonialTypeEnum";

export interface Testimonial {
  /** @maxLength 255 */
  client_name: string;
  /** @maxLength 255 */
  company?: string;
  /** The date and time when this record was created. */
  readonly created_at: string;
  /**
   * @minimum -9223372036854776000
   * @maximum 9223372036854776000
   */
  display_order?: number;
  /** Unique identifier for this record. */
  readonly id: string;
  is_featured?: boolean;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  logo?: string | null;
  readonly logo_url: string;
  /**
   * @minimum 0
   * @maximum 9223372036854776000
   */
  rating?: number;
  review_text: string;
  /** @maxLength 255 */
  role?: string;
  status?: Status227Enum;
  testimonial_type?: TestimonialTypeEnum;
  /** The date and time when this record was last updated. */
  readonly updated_at: string;
  /**
   * Unique identifier for this record.
   * @nullable
   */
  video?: string | null;
  readonly video_url: string;
}
