/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `Client` - Client
 * `Partner` - Partner
 * `Investor` - Investor
 * `Mentor` - Mentor
 * `Employee` - Employee
 */
export type TestimonialTypeEnum =
  (typeof TestimonialTypeEnum)[keyof typeof TestimonialTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestimonialTypeEnum = {
  Client: "Client",
  Partner: "Partner",
  Investor: "Investor",
  Mentor: "Mentor",
  Employee: "Employee",
} as const;
