/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface TimelineEvent {
  /**
   * User ID of the actor
   * @nullable
   */
  actor_id?: string | null;
  content_type: number;
  readonly content_type_model: string;
  readonly created_at: string;
  description?: string;
  /** @maxLength 100 */
  event_type: string;
  readonly id: string;
  metadata?: string;
  /** @nullable */
  object_id?: string | null;
  /** @maxLength 255 */
  title: string;
}
