/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TrendSectionData } from "./trendSectionData";

export interface TrendSection {
  /** @nullable */
  data?: TrendSectionData;
  enabled: boolean;
}
