/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `INFO` - Info
 * `SUCCESS` - Success
 * `NOTICE` - Notice
 * `WARNING` - Warning
 * `CRITICAL` - Critical
 */
export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeEnum = {
  INFO: "INFO",
  SUCCESS: "SUCCESS",
  NOTICE: "NOTICE",
  WARNING: "WARNING",
  CRITICAL: "CRITICAL",
} as const;
