/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for user update (PATCH) requests.
 */
export interface UserUpdate {
  email?: string;
  /** @maxLength 150 */
  first_name?: string;
  groups?: string[];
  is_active?: boolean;
  is_staff?: boolean;
  is_superuser?: boolean;
  /** @maxLength 150 */
  last_name?: string;
}
