/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { Group } from "./group";

export interface User {
  /** @maxLength 254 */
  email: string;
  /** @maxLength 150 */
  first_name?: string;
  readonly groups: readonly Group[];
  /** Unique identifier for this record. */
  readonly id: string;
  /** Designates whether the user can log into this admin site. */
  is_staff?: boolean;
  /** Designates that this user has all permissions without explicitly assigning them. */
  is_superuser?: boolean;
  /** @maxLength 150 */
  last_name?: string;
  readonly permissions: readonly string[];
  /** @nullable */
  readonly role: string | null;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
}
