/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ExecutiveMetricsSection } from "./executiveMetricsSection";
import type { TrendSection } from "./trendSection";
import type { PlatformInsightsSection } from "./platformInsightsSection";

export interface UserAnalyticsResponse {
  executive_metrics: ExecutiveMetricsSection;
  permission_distribution: TrendSection;
  role_distribution: TrendSection;
  user_growth: TrendSection;
  user_insights: PlatformInsightsSection;
}
