/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `STRING` - String
 * `INTEGER` - Integer
 * `BOOLEAN` - Boolean
 * `FLOAT` - Float
 * `JSON` - JSON
 * `EMAIL` - Email
 * `URL` - URL
 */
export type ValueTypeEnum = (typeof ValueTypeEnum)[keyof typeof ValueTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValueTypeEnum = {
  STRING: "STRING",
  INTEGER: "INTEGER",
  BOOLEAN: "BOOLEAN",
  FLOAT: "FLOAT",
  JSON: "JSON",
  EMAIL: "EMAIL",
  URL: "URL",
} as const;
