/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `PUBLIC` - Public
 * `AUTHENTICATED` - Authenticated
 * `GUEST` - Guest
 */
export type VisibilityEnum =
  (typeof VisibilityEnum)[keyof typeof VisibilityEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VisibilityEnum = {
  PUBLIC: "PUBLIC",
  AUTHENTICATED: "AUTHENTICATED",
  GUEST: "GUEST",
} as const;
