/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

export const healthRetrieve2Response = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "status": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

