/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

/**
 * @summary List published knowledge base articles (public)
 */
export const kbEntriesListQueryParams = zod.object({
  "category": zod.string().optional(),
  "search": zod.string().optional()
})

export const kbEntriesListResponseDataItemCategoryNameMax = 100;
export const kbEntriesListResponseDataItemCategorySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const kbEntriesListResponseDataItemCategoryColorMax = 20;
export const kbEntriesListResponseDataItemCategoryIconMax = 50;
export const kbEntriesListResponseDataItemCategorySortOrderMin = 0;

export const kbEntriesListResponseDataItemCategorySortOrderMax = 9223372036854776000;
export const kbEntriesListResponseDataItemTagsItemNameMax = 50;
export const kbEntriesListResponseDataItemTagsItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const kbEntriesListResponseDataItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const kbEntriesListResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.array(zod.object({
  "id": zod.string().uuid(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string().max(kbEntriesListResponseDataItemCategoryNameMax),
  "slug": zod.string().regex(kbEntriesListResponseDataItemCategorySlugRegExp),
  "color": zod.string().max(kbEntriesListResponseDataItemCategoryColorMax).optional(),
  "icon": zod.string().max(kbEntriesListResponseDataItemCategoryIconMax).optional(),
  "sort_order": zod.number().min(kbEntriesListResponseDataItemCategorySortOrderMin).max(kbEntriesListResponseDataItemCategorySortOrderMax).optional(),
  "is_active": zod.boolean().optional()
}),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string().max(kbEntriesListResponseDataItemTagsItemNameMax),
  "slug": zod.string().regex(kbEntriesListResponseDataItemTagsItemSlugRegExp),
  "is_active": zod.boolean().optional()
})),
  "title": zod.string(),
  "slug": zod.string().regex(kbEntriesListResponseDataItemSlugRegExp),
  "status": zod.enum(['draft', 'published', 'archived']),
  "source": zod.enum(['manual', 'json_import', 'api']),
  "sort_order": zod.number(),
  "published_at": zod.string().datetime().nullable(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime()
})),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

/**
 * @summary Retrieve a published knowledge base article by slug (public)
 */
export const kbEntriesRetrieveParams = zod.object({
  "slug": zod.string()
})

export const kbEntriesRetrieveResponseDataCategoryNameMax = 100;
export const kbEntriesRetrieveResponseDataCategorySlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const kbEntriesRetrieveResponseDataCategoryColorMax = 20;
export const kbEntriesRetrieveResponseDataCategoryIconMax = 50;
export const kbEntriesRetrieveResponseDataCategorySortOrderMin = 0;

export const kbEntriesRetrieveResponseDataCategorySortOrderMax = 9223372036854776000;
export const kbEntriesRetrieveResponseDataTagsItemNameMax = 50;
export const kbEntriesRetrieveResponseDataTagsItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const kbEntriesRetrieveResponseDataSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');


export const kbEntriesRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string().uuid(),
  "category": zod.object({
  "id": zod.number(),
  "name": zod.string().max(kbEntriesRetrieveResponseDataCategoryNameMax),
  "slug": zod.string().regex(kbEntriesRetrieveResponseDataCategorySlugRegExp),
  "color": zod.string().max(kbEntriesRetrieveResponseDataCategoryColorMax).optional(),
  "icon": zod.string().max(kbEntriesRetrieveResponseDataCategoryIconMax).optional(),
  "sort_order": zod.number().min(kbEntriesRetrieveResponseDataCategorySortOrderMin).max(kbEntriesRetrieveResponseDataCategorySortOrderMax).optional(),
  "is_active": zod.boolean().optional()
}),
  "tags": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string().max(kbEntriesRetrieveResponseDataTagsItemNameMax),
  "slug": zod.string().regex(kbEntriesRetrieveResponseDataTagsItemSlugRegExp),
  "is_active": zod.boolean().optional()
})),
  "title": zod.string(),
  "slug": zod.string().regex(kbEntriesRetrieveResponseDataSlugRegExp),
  "status": zod.enum(['draft', 'published', 'archived']),
  "source": zod.enum(['manual', 'json_import', 'api']),
  "sort_order": zod.number(),
  "published_at": zod.string().datetime().nullable(),
  "created_at": zod.string().datetime(),
  "updated_at": zod.string().datetime(),
  "content": zod.string(),
  "structured_data": zod.any(),
  "created_by": zod.string(),
  "updated_by": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

