/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { HealthRetrieve2200 } from "../../model";
import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const healthRetrieve = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/api/v1/health/`, method: "GET", signal },
    options,
  );
};

export const getHealthRetrieveQueryKey = () => {
  return [`/api/v1/health/`] as const;
};

export const getHealthRetrieveQueryOptions = <
  TData = Awaited<ReturnType<typeof healthRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthRetrieve>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthRetrieveQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthRetrieve>>> = ({
    signal,
  }) => healthRetrieve(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthRetrieve>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthRetrieveQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthRetrieve>>
>;
export type HealthRetrieveQueryError = unknown;

export const useHealthRetrieve = <
  TData = Awaited<ReturnType<typeof healthRetrieve>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthRetrieve>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHealthRetrieveQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const healthRetrieve2 = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<HealthRetrieve2200>(
    { url: `/health/`, method: "GET", signal },
    options,
  );
};

export const getHealthRetrieve2QueryKey = () => {
  return [`/health/`] as const;
};

export const getHealthRetrieve2QueryOptions = <
  TData = Awaited<ReturnType<typeof healthRetrieve2>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthRetrieve2>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthRetrieve2QueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthRetrieve2>>> = ({
    signal,
  }) => healthRetrieve2(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthRetrieve2>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthRetrieve2QueryResult = NonNullable<
  Awaited<ReturnType<typeof healthRetrieve2>>
>;
export type HealthRetrieve2QueryError = unknown;

export const useHealthRetrieve2 = <
  TData = Awaited<ReturnType<typeof healthRetrieve2>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthRetrieve2>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getHealthRetrieve2QueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
