/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import type {
  ChatCreate200,
  ChatFeedbackCreate200,
  ChatRequestRequest,
  ChatSessionCreateRequestRequest,
  ChatSessionsCreate200,
  FeedbackCreateRequest,
} from "../../model";
import { customInstance } from "../../mutator/custom-instance";

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const chatCreate = (
  chatRequestRequest: ChatRequestRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ChatCreate200>(
    {
      url: `/api/v1/chat/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: chatRequestRequest,
    },
    options,
  );
};

export const getChatCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatCreate>>,
    TError,
    { data: ChatRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatCreate>>,
  TError,
  { data: ChatRequestRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatCreate>>,
    { data: ChatRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return chatCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatCreate>>
>;
export type ChatCreateMutationBody = ChatRequestRequest;
export type ChatCreateMutationError = unknown;

export const useChatCreate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatCreate>>,
    TError,
    { data: ChatRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof chatCreate>>,
  TError,
  { data: ChatRequestRequest },
  TContext
> => {
  const mutationOptions = getChatCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const chatFeedbackCreate = (
  feedbackCreateRequest: FeedbackCreateRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ChatFeedbackCreate200>(
    {
      url: `/api/v1/chat/feedback/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: feedbackCreateRequest,
    },
    options,
  );
};

export const getChatFeedbackCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatFeedbackCreate>>,
    TError,
    { data: FeedbackCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatFeedbackCreate>>,
  TError,
  { data: FeedbackCreateRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatFeedbackCreate>>,
    { data: FeedbackCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return chatFeedbackCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatFeedbackCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatFeedbackCreate>>
>;
export type ChatFeedbackCreateMutationBody = FeedbackCreateRequest;
export type ChatFeedbackCreateMutationError = unknown;

export const useChatFeedbackCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatFeedbackCreate>>,
    TError,
    { data: FeedbackCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof chatFeedbackCreate>>,
  TError,
  { data: FeedbackCreateRequest },
  TContext
> => {
  const mutationOptions = getChatFeedbackCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
export const chatSessionsCreate = (
  chatSessionCreateRequestRequest: ChatSessionCreateRequestRequest,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ChatSessionsCreate200>(
    {
      url: `/api/v1/chat/sessions/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: chatSessionCreateRequestRequest,
    },
    options,
  );
};

export const getChatSessionsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatSessionsCreate>>,
    TError,
    { data: ChatSessionCreateRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chatSessionsCreate>>,
  TError,
  { data: ChatSessionCreateRequestRequest },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chatSessionsCreate>>,
    { data: ChatSessionCreateRequestRequest }
  > = (props) => {
    const { data } = props ?? {};

    return chatSessionsCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChatSessionsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof chatSessionsCreate>>
>;
export type ChatSessionsCreateMutationBody = ChatSessionCreateRequestRequest;
export type ChatSessionsCreateMutationError = unknown;

export const useChatSessionsCreate = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chatSessionsCreate>>,
    TError,
    { data: ChatSessionCreateRequestRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof chatSessionsCreate>>,
  TError,
  { data: ChatSessionCreateRequestRequest },
  TContext
> => {
  const mutationOptions = getChatSessionsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
