/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * B10 Business OS & Platform API
 * Enterprise Solution Architecture, RBAC Identity, and Business Operations REST API.
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod'

export const authChangePasswordCreateBody = zod.object({
  "old_password": zod.string().min(1),
  "new_password": zod.string().min(1)
})

export const authChangePasswordCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "success": zod.boolean(),
  "message": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

/**
 * Takes a set of user credentials and returns an access and refresh JSON web
token pair to prove the authentication of those credentials.
 */
export const authLoginCreateBody = zod.object({
  "email": zod.string().min(1),
  "password": zod.string().min(1)
})

export const authLoginCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "detail": zod.string(),
  "user": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const authLogoutCreateBody = zod.object({
  "refresh": zod.string().min(1).optional()
})

export const authLogoutCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "detail": zod.string()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const authMeRetrieveResponseDataUsernameMax = 150;

export const authMeRetrieveResponseDataUsernameRegExp = new RegExp('^[\\w.@+-]+$');
export const authMeRetrieveResponseDataEmailMax = 254;
export const authMeRetrieveResponseDataFirstNameMax = 150;
export const authMeRetrieveResponseDataLastNameMax = 150;
export const authMeRetrieveResponseDataGroupsItemNameMax = 150;


export const authMeRetrieveResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string().uuid(),
  "username": zod.string().max(authMeRetrieveResponseDataUsernameMax).regex(authMeRetrieveResponseDataUsernameRegExp),
  "email": zod.string().email().max(authMeRetrieveResponseDataEmailMax),
  "first_name": zod.string().max(authMeRetrieveResponseDataFirstNameMax).optional(),
  "last_name": zod.string().max(authMeRetrieveResponseDataLastNameMax).optional(),
  "role": zod.string().nullable(),
  "groups": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string().max(authMeRetrieveResponseDataGroupsItemNameMax)
})),
  "permissions": zod.array(zod.string()),
  "is_superuser": zod.boolean().optional(),
  "is_staff": zod.boolean().optional()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

export const authMePartialUpdateBodyFirstNameMax = 150;
export const authMePartialUpdateBodyLastNameMax = 150;
export const authMePartialUpdateBodyEmailMax = 254;
export const authMePartialUpdateBodyUsernameMax = 150;

export const authMePartialUpdateBodyUsernameRegExp = new RegExp('^[\\w.@+-]+$');


export const authMePartialUpdateBody = zod.object({
  "first_name": zod.string().max(authMePartialUpdateBodyFirstNameMax).optional(),
  "last_name": zod.string().max(authMePartialUpdateBodyLastNameMax).optional(),
  "email": zod.string().email().min(1).max(authMePartialUpdateBodyEmailMax).optional(),
  "username": zod.string().min(1).max(authMePartialUpdateBodyUsernameMax).regex(authMePartialUpdateBodyUsernameRegExp).optional()
})

export const authMePartialUpdateResponseDataUsernameMax = 150;

export const authMePartialUpdateResponseDataUsernameRegExp = new RegExp('^[\\w.@+-]+$');
export const authMePartialUpdateResponseDataEmailMax = 254;
export const authMePartialUpdateResponseDataFirstNameMax = 150;
export const authMePartialUpdateResponseDataLastNameMax = 150;
export const authMePartialUpdateResponseDataGroupsItemNameMax = 150;


export const authMePartialUpdateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "id": zod.string().uuid(),
  "username": zod.string().max(authMePartialUpdateResponseDataUsernameMax).regex(authMePartialUpdateResponseDataUsernameRegExp),
  "email": zod.string().email().max(authMePartialUpdateResponseDataEmailMax),
  "first_name": zod.string().max(authMePartialUpdateResponseDataFirstNameMax).optional(),
  "last_name": zod.string().max(authMePartialUpdateResponseDataLastNameMax).optional(),
  "role": zod.string().nullable(),
  "groups": zod.array(zod.object({
  "id": zod.number(),
  "name": zod.string().max(authMePartialUpdateResponseDataGroupsItemNameMax)
})),
  "permissions": zod.array(zod.string()),
  "is_superuser": zod.boolean().optional(),
  "is_staff": zod.boolean().optional()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authRefreshCreateBody = zod.object({
  "refresh": zod.string().min(1)
})

export const authRefreshCreateResponse = zod.object({
  "success": zod.boolean(),
  "data": zod.object({
  "access": zod.string(),
  "refresh": zod.string().optional()
}),
  "message": zod.string().optional(),
  "meta": zod.object({
  "request_id": zod.string().optional(),
  "timestamp": zod.string().datetime().optional(),
  "execution_time_ms": zod.number().optional(),
  "pagination": zod.boolean().optional()
})
})

